Volume mount operation is added
srijan-sivakumar/Redant pull request #13
Opened 2021-03-08 11:17 UTC by nishith-vihar

Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-03-08 13:20 UTC, srijan-sivakumar commented on redant_libs/volume_ops.py
> +    #TODO: to be removed later
What is this todo for ? If it is for validation, we can start working on it rather than leaving that as debt for later.

2021-03-08 13:52 UTC, nishith-vihar commented on redant_libs/volume_ops.py
> +    #TODO: to be removed later
Actually the ip address for the node has to come from config file I guess. The parsing module is not yet connected to ops. So I have just hard-coded the ip for testing.

2021-03-09 05:48 UTC, srijan-sivakumar requested changes

2021-03-09 05:48 UTC, srijan-sivakumar commented on redant_libs/volume_ops.py
> +    #TODO: to be removed later
ok, but this seems to be for the print

2021-03-09 05:48 UTC, srijan-sivakumar commented on redant_libs/volume_ops.py
> +    node = "10.70.43.63"
We can pass this as an argument rather than hardcoding in here the function.

2021-03-09 05:48 UTC, srijan-sivakumar commented on redant_libs/volume_ops.py
> +    node = "10.70.43.63"
I'd recommend not to create this debt in here as we'd just keep on piling such additions across the code. Focus on adding the parser into the code-base, write a sample TC even if it is for a couple of lines.

2021-03-09 05:54 UTC, nishith-vihar commented on redant_libs/volume_ops.py
> +    #TODO: to be removed later
yeah. Actually the print is for testing the return value which has to be removed.

2021-03-12 06:55 UTC, srijan-sivakumar requested changes
Do refer to the latest design considerations. I'll add a readme.md stating python coding considerations, but those can go as a separate PR but do check out the peer_ops on how an ops lib is re-deisnged.

2021-03-12 06:55 UTC, srijan-sivakumar commented on redant_libs/gluster_libs/volume_ops.py
>  R = Rexe(conf_path="./example/conf.yaml")
Not required in the ops libraries from now on.

2021-03-12 06:55 UTC, srijan-sivakumar commented on redant_libs/gluster_libs/volume_ops.py
> +def volume_mount(mnode , volname , path,force=False):
use the function annotations.

2021-03-12 06:55 UTC, srijan-sivakumar commented on redant_libs/gluster_libs/volume_ops.py
> +    RR.rlogger.info("Volume Mount Command initiated")
Refer the peer_ops for reference on the usage of logging and call to remote command executor.

2021-03-12 06:55 UTC, srijan-sivakumar commented on redant_libs/gluster_libs/volume_ops.py
> +    node = "10.70.43.63"
Remove this hard coded value from code. To test the functions, we should only create small TCs. Not to be done here directly.

2021-03-12 07:03 UTC, nishith-vihar commented on redant_libs/gluster_libs/volume_ops.py
> +    node = "10.70.43.63"
Please refer to #24

2021-03-12 07:39 UTC, closed without merging