Functionalities are added in ops lib
srijan-sivakumar/redant pull request #141
Opened 2021-03-29 13:32 UTC by neesingh-rh

More options are added in mkdir.
rmdir and file_exists functions are added.

Updates: #135 
Signed-off-by: Neeraj Pratap Singh neesingh@redhat.com

2021-03-29 13:55 UTC, srijan-sivakumar requested changes
Please rebase and send out the patch. Also, can you add some supporting TCs to verify these functionalities ?

2021-03-29 14:20 UTC, neesingh-rh commented
> Please rebase and send out the patch. Also, can you add some supporting TCs to verify these functionalities ?

Yeah..I will add TCs .

2021-04-08 16:45 UTC, srijan-sivakumar reviewed
@neesingh-rh , just rebase and check if there are any conflicts with the test_comparison.py

2021-04-08 17:03 UTC, neesingh-rh commented
> @neesingh-rh , just rebase and check if there are any conflicts with the test_comparison.py

There are no conflicts.

2021-04-08 17:05 UTC, neesingh-rh commented
I have added the new test case with the modifications to handle non-volume TCs.I did run the TC with modifications, it is running.

2021-04-09 05:30 UTC, nishith-vihar commented on support/ops/gluster_ops/peer_ops.py
> +            list : list of dicts on success.
You can give an example format of the list of dicts returned.

2021-04-09 05:30 UTC, nishith-vihar commented on tests/example/test_comparison.py
> +"""
Why is the test_comparison file added again example?

2021-04-09 05:30 UTC, nishith-vihar commented on tests/functional/glusterd/test_comparison.py
> +# disruptive;dist
Space should not be added in the volume types comment as it will be parsed by comment parser.

2021-04-09 05:30 UTC, nishith-vihar commented on tests/example/test_file_creation.py
> +"""
Why is the same file added in both example and glusterd?

2021-04-09 05:48 UTC, srijan-sivakumar approved these changes

2021-04-09 05:48 UTC, merged