Enhancing the config file
srijan-sivakumar/redant pull request #151
Opened 2021-03-31 07:39 UTC by nishith-vihar

The mount info is removed and the servers section is removed
from the volume info part.

Fixes: #150
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-03-31 16:12 UTC, BarakSason commented
I think lines 144 to 146 can be removed as well.
In addition, please move the config file from /core/congif to /config.

2021-03-31 16:13 UTC, BarakSason requested changes
I think lines 144 to 146 can be removed as well.
In addition, please move the config file from /core/parsing to /config.

2021-04-05 05:28 UTC, srijan-sivakumar requested changes
L69-L70 can be removed I think. The comment says `this is to define what volume types and mount protocols will be run in this current test run.`

2021-04-05 06:03 UTC, srijan-sivakumar approved these changes

2021-04-05 06:04 UTC, merged