Modified the peer ops file
srijan-sivakumar/redant pull request #183
Opened 2021-04-12 04:59 UTC by aujjwal-redhat

Added the return types in function.
Removed the non-matching docstrings.

Fixes: #182

Signed-off-by: aujjwal-redhat <aujjwal@redhat.com>

2021-04-12 05:06 UTC, srijan-sivakumar requested changes

2021-04-12 05:06 UTC, srijan-sivakumar commented on support/ops/gluster_ops/peer_ops.py
> -        return ret
Any specific reason as to why the return value is being removed?
What if the TC demands that the response of peer probe is to be checked if it remains the same after multiple peer probe and detach commands. There are certain glusto TCs which perform this type of operation.

2021-04-12 05:06 UTC, srijan-sivakumar commented on support/ops/gluster_ops/peer_ops.py
> -        return ret
Same as above.

2021-04-12 05:06 UTC, srijan-sivakumar commented on support/ops/gluster_ops/peer_ops.py
> -        return ret
Same as above.

2021-04-12 05:07 UTC, aujjwal-redhat commented on support/ops/gluster_ops/peer_ops.py
> -        return ret
Oh ok. Will add ret then.

2021-04-12 05:07 UTC, aujjwal-redhat commented on support/ops/gluster_ops/peer_ops.py
> -        return ret
Ack

2021-04-12 05:09 UTC, neesingh-rh approved these changes

2021-04-12 08:13 UTC, aujjwal-redhat commented on support/ops/gluster_ops/peer_ops.py
> -        return ret
@srijan-sivakumar is it fine now?

2021-04-15 05:05 UTC, srijan-sivakumar approved these changes
LGTM

2021-04-15 05:05 UTC, merged