Abstract Ops is added
srijan-sivakumar/redant pull request #191
Opened 2021-04-12 12:29 UTC by nishith-vihar

Abstract Ops is added and ops libraries are accodingly modified
to inherit the abstract ops.

Fixes: #153
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-04-15 13:30 UTC, srijan-sivakumar commented
@nishith-vihar , let's take this to draft stage till we take it up again.

2021-04-15 13:33 UTC, nishith-vihar commented
> @nishith-vihar , let's take this to draft stage till we take it up again.

Ack

2021-04-20 07:11 UTC, srijan-sivakumar commented
As the logging now doesn't go into the file level details, @nishith-vihar , I think we can pursue this PR..

2021-04-20 10:58 UTC, srijan-sivakumar commented
@nishith-vihar , try to rebase and see what all new changes went through..

2021-04-20 12:03 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_peer_probe_detach.py
> +        redant.peer_detach(server2,server1)
We actually have a destroy cluster module in the framework, I suggest we use that here

2021-04-20 12:03 UTC, srijan-sivakumar commented on support/ops/gluster_ops/peer_ops.py
> +        ret = self.execute_abstract_op_node(cmd,node)
nit: ret = self.execute_abstract_op_node(cmd, node)

2021-04-20 12:04 UTC, srijan-sivakumar commented on support/ops/gluster_ops/volume_ops.py
> +        ret = self.execute_abstract_op_node(cmd,node)
NIT: add a space after `,`

2021-04-20 12:05 UTC, srijan-sivakumar requested changes
Do check the added comments.

2021-04-20 12:07 UTC, nishith-vihar commented on support/ops/gluster_ops/peer_ops.py
> +        ret = self.execute_abstract_op_node(cmd,node)
Ack

2021-04-20 12:07 UTC, nishith-vihar commented on support/ops/gluster_ops/volume_ops.py
> +        ret = self.execute_abstract_op_node(cmd,node)
Ack

2021-04-20 12:08 UTC, nishith-vihar commented on tests/functional/glusterd/test_peer_probe_detach.py
> +        redant.peer_detach(server2,server1)
Ack

2021-04-21 12:13 UTC, srijan-sivakumar approved these changes

2021-04-21 12:13 UTC, merged