Added linting and flaking script
srijan-sivakumar/redant pull request #192
Opened 2021-04-14 08:33 UTC by aujjwal-redhat

Added a script that will provide automatic flaking and linting of the files.

Fixes : #181

Signed-off-by: aujjwal-redhat <aujjwal@redhat.com>

2021-04-14 08:41 UTC, nik-redhat commented on scripts/flake_lint.sh
> +    echo 'Performing both flaking and linting'
I don't think `Flaking` is a valid word :sweat_smile: 
Please do update it in all the areas, if others agree too.

2021-04-14 08:42 UTC, nik-redhat commented
Also, while you are doing other changes, mentioning this in the contributing guide would be helpful along with the optional args it takes.

2021-04-14 08:49 UTC, aujjwal-redhat commented
> Also, while you are doing other changes, mentioning this in the contributing guide would be helpful along with the optional args it takes.

Yeah it's still a draft. I am already working on creating a separate markdown for this script as well. I will add the reference to this md in the contributing.md file as well.

2021-04-14 08:49 UTC, aujjwal-redhat commented on scripts/flake_lint.sh
> +    echo 'Performing both flaking and linting'
oh ok

2021-04-14 14:35 UTC, srijan-sivakumar requested changes
We already have a tools directory, please add the script to that dir itself.

2021-04-14 14:36 UTC, srijan-sivakumar commented on scripts/README.md
> +./scripts/flake_lint.sh . [flake/lint]
Best practice would be to have a flag to switch between path based and complete repo linting.

2021-04-14 14:38 UTC, srijan-sivakumar commented on scripts/flake_lint.sh
> +# NARGS stores the number of arguments passed
Let's just call the script as linting.sh as this uses both flake and pylint tools which is nothing but code linting.

2021-04-14 14:39 UTC, srijan-sivakumar reviewed
@aujjwal-redhat do run the `shellcheck` on the script and see if there are any issues. Probably we should edit the Contributing to add information about what checks are to be performed for shell files before code is pushed.

2021-04-14 14:42 UTC, srijan-sivakumar commented on scripts/flake_lint.sh
> +elif [[ $OPERATION == 'flake' ]]
Again..Flag based approach would be better, rather than naming the operation. Also do add a `help` function which will be displayed on two scenarios,
1. When user gives `--help` flag after the script.
2. When the user uses a wrong flag or doesn't provide proper information. The standard practice in this scenario would be to display the command information along with the flags and their meaning rather than taking further input from user. [ This I believe can be handled by our help function ]

2021-04-15 04:33 UTC, aujjwal-redhat commented on scripts/flake_lint.sh
> +# NARGS stores the number of arguments passed
Ack

2021-04-15 04:34 UTC, aujjwal-redhat commented on scripts/flake_lint.sh
> +elif [[ $OPERATION == 'flake' ]]
Let's take the python approach then. That would be more robust.

2021-04-15 08:15 UTC, srijan-sivakumar requested changes

2021-04-15 08:15 UTC, srijan-sivakumar commented on tools/linting.sh
> +        \?)
NIT: Do add a stdout statement saying the flag is erroneous. Or else this is similar to the operation when we use help as flag.

2021-04-15 08:20 UTC, aujjwal-redhat commented on tools/linting.sh
> +        \?)
It already says
```js
(redantenv) [root@serverc redant]# tools/linting.sh -d
tools/linting.sh: illegal option -- d
Linting help
=============
Flags:
-p : Specifies the path of the file
    Ex: tools/linting.sh -p /home/redant/core

-f : Specifies flake operation to be performed only
    Ex: If you want to test flake for core
        tools/linting.sh -p /home/redant/core -f

-l : Specifies lint operation to be performed only
    Ex: If you want to test lint for core
        tools/linting.sh -p /home/redant/core -l

-h : Provides the information about the flags

Note:
=====
If you don't specify the path, the operation will occur on the whole repo

Ex: tools/linting.sh -f -l
This will perform the linting on the whoke repo

Examples:
=========
tools/linting.sh -p /home/redant/core

```

2021-04-15 08:21 UTC, aujjwal-redhat commented on tools/linting.sh
> +        \?)
I have to update the examples as well. Will do that now. In that will specify more information

2021-04-15 08:27 UTC, aujjwal-redhat commented
@srijan-sivakumar have updated the help
```js
(redantenv) [root@serverc redant]# tools/linting.sh -d
tools/linting.sh: illegal option -- d

Linting help
=============
Flags:
-p : Specifies the path of the file
    Ex: tools/linting.sh -p /home/redant/core

-f : Specifies flake operation to be performed only
    Ex: If you want to test flake for core
        tools/linting.sh -p /home/redant/core -f

-l : Specifies lint operation to be performed only
    Ex: If you want to test lint for core
        tools/linting.sh -p /home/redant/core -l

-h : Provides the information about the flags

Note:
=====
If you don't specify the path, the operation will occur on the whole repo

Ex: tools/linting.sh -f -l
This will perform the linting on the whole repo

Examples:
=========
tools/linting.sh -f
This will perform only flake on the folder

tools/linting.sh -l
This will perform only lint on the folder

tools/linting.sh -p /home/redant/core -f -l
This will perform linting on the folder

tools/linting.sh -p /home/redant/core -f
This will perform only flake operation on the folder

tools/linting.sh -p /home/redant/core -l
This will perform only lint operation on the folder

tools/linting.sh -[wrong flag]
This will show illegal action
```

2021-04-15 08:51 UTC, srijan-sivakumar commented
@neesingh-rh @nishith-vihar do review the patch.

2021-04-15 12:14 UTC, aujjwal-redhat commented
@nishith-vihar @neesingh-rh lemme know if the script is fine.

2021-04-15 13:44 UTC, nishith-vihar approved these changes
LGTM

2021-04-15 13:58 UTC, srijan-sivakumar approved these changes
LGTM

2021-04-15 13:58 UTC, merged