Added procedure to write a test case
srijan-sivakumar/redant pull request #199
Opened 2021-04-15 12:47 UTC by aujjwal-redhat

Added the steps to write a test case from scratch

Fixes: #198

Signed-off-by: aujjwal-redhat <aujjwal@redhat.com>

2021-04-15 13:04 UTC, neesingh-rh commented on tests/README.md
> +```
We can give example for mentioning volume type along with this eg-disruptive;dist
Rest looks fine to me

2021-04-15 13:23 UTC, aujjwal-redhat commented on tests/README.md
> +```
Ack

2021-04-15 13:26 UTC, aujjwal-redhat commented on tests/README.md
> +```
Actually volume table is specified in the table above already so I will put it's reference here.

2021-04-15 13:29 UTC, srijan-sivakumar requested changes
I'd say we write it an explanatory manner. Imagine yourself to be a user who doesn't know this framework and wants to write the TC. The steps are always good but maybe we can add a little bit of flair to the writing so that it isn't dry.

Maybe treat the readme like a blog..I think that might be a good approach here.

2021-04-15 13:29 UTC, srijan-sivakumar commented on tests/README.md
> +6. Make a function `run_test`. This function basically overrides the run test function from the [Parent Test](https://github.com/srijan-sivakumar/redant/blob/main/tests/parent_test.py)
How about we explain when to add __init__, and terminate also ? Because there might be cases wherein the user would have to override the existing functions ( Though we would have to invoke the parent test's constructor and terminate ourselves inside the TC ).

2021-04-15 13:32 UTC, aujjwal-redhat commented on tests/README.md
> +6. Make a function `run_test`. This function basically overrides the run test function from the [Parent Test](https://github.com/srijan-sivakumar/redant/blob/main/tests/parent_test.py)
Ack

2021-04-16 15:58 UTC, srijan-sivakumar approved these changes
:) LGTM

2021-04-16 15:58 UTC, merged