Check is added for existence and accessibility of config_file
srijan-sivakumar/redant pull request #232
Opened 2021-04-29 12:04 UTC by nishith-vihar

Check is added for existence and accessibility of config_file
Fixes: #231
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-04-29 15:46 UTC, srijan-sivakumar requested changes

2021-04-29 15:46 UTC, srijan-sivakumar commented on core/redant_main.py
> +    if os.access(args.config_file, os.R_OK):
The check should be inside the paramhandler and not redant_main.

2021-05-03 13:14 UTC, srijan-sivakumar requested changes

2021-05-03 13:14 UTC, srijan-sivakumar commented on core/parsing/test_parser.py
> +            raise IOError
Rather than adding a try catch here, let's just add a function which check the file exists or not. For example let's call the function 'file_accessible'. hence the line 25-31 can be converted into..

```
if not file_accessible(filepath, <permissions>):
    raise IOError
configfd = open(filepath, 'r')
config_hashmap = yaml.load(configfd, Loader=yaml.FullLoader)
configfd.close()
```

Now this IOError can be caught at the main in a try catch. So we just need to declutter a little by replacing the try-except inside params with just a `raise IOError`.

2021-05-03 13:37 UTC, nishith-vihar commented on core/parsing/test_parser.py
> +            raise IOError
Ack

2021-05-04 10:53 UTC, srijan-sivakumar approved these changes
LGTM

2021-05-04 10:54 UTC, merged