Added the passwordless ssh code in rexe
srijan-sivakumar/redant pull request #233
Opened 2021-04-29 12:48 UTC by aujjwal-redhat

Added the passwordless ssh code in the remote executioner. Now no user
name or password is required. To test the same you need to setup the
passwordless ssh on your servers.

Note: Setup passwordless ssh from one server to another server and from
one server to the same server as well.

Fixes: #154

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-04-29 15:49 UTC, srijan-sivakumar commented
> Added the passwordless ssh code in the remote executioner. Now no user
> name or password is required. To test the same you need to setup the
> passwordless ssh on your servers.
> 
> Note: Setup passwordless ssh from one server to another server and from
> one server to the same server as well.
Do you mean to say that the keys should be shared between all servers ? Like for instance we have servera, serverb and serverc along with a control_machine where we run the test framework, so do we need to setup passwordless ssh between all four machines ? If yes then why do the servers require to access the control_machine ? I can understand if we need to setup passwordless ssh between server{a, b, c} as it'd also help for geo-replication, but not the scenario where anyone from server{a, b, c} can access control_machine.

> Fixes: #154
> 
> Signed-off-by: Ayush Ujjwal [aujjwal@redhat.com](mailto:aujjwal@redhat.com)

2021-04-29 15:55 UTC, srijan-sivakumar requested changes

2021-04-29 15:55 UTC, srijan-sivakumar commented on common/rexe.py
> +import os
The standards dictate that we put imports of standard modules at the very top. Hence os will come before xmltodict which is a third party module.

2021-04-29 15:55 UTC, srijan-sivakumar commented on common/rexe.py
> +            # paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
Again. Not a good practice. We should have this setting in the config or in command line flag. Not as a comment and tell user to comment/uncomment it.

2021-04-29 15:55 UTC, srijan-sivakumar commented on common/rexe.py
>                  paramiko.AutoAddPolicy())
Do we still need to keep AutoAddPolicy ? Even after setting the keys ? This is actually a security threat. See if this can be changed.

2021-04-29 15:55 UTC, srijan-sivakumar commented on common/rexe.py
>                      hostname=node,
is it necessary to give `hostname=node` and `pkey=mkey` ? Just curious.

2021-04-30 04:29 UTC, aujjwal-redhat commented
> > Added the passwordless ssh code in the remote executioner. Now no user
> > name or password is required. To test the same you need to setup the
> > passwordless ssh on your servers.
> > Note: Setup passwordless ssh from one server to another server and from
> > one server to the same server as well.
> 
> Do you mean to say that the keys should be shared between all servers ? Like for instance we have servera, serverb and serverc along with a control_machine where we run the test framework, so do we need to setup passwordless ssh between all four machines ? If yes then why do the servers require to access the control_machine ? I can understand if we need to setup passwordless ssh between server{a, b, c} as it'd also help for geo-replication, but not the scenario where anyone from server{a, b, c} can access control_machine.
> 
> > Fixes: #154
> > Signed-off-by: Ayush Ujjwal [aujjwal@redhat.com](mailto:aujjwal@redhat.com)

You are right @srijan-sivakumar but I meant only the servers not the servers to the control machine. In that case, obviously, the servers can get access to the same and can cause damage to the framework as well.

2021-04-30 04:29 UTC, aujjwal-redhat commented on common/rexe.py
> +import os
Oh ok. Will make the change.

2021-04-30 04:29 UTC, aujjwal-redhat commented on common/rexe.py
> +            # paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
Yeah true.

2021-04-30 04:30 UTC, aujjwal-redhat commented on common/rexe.py
>                  paramiko.AutoAddPolicy())
Yeah actually I was going to ask the same. Will remove that as it is not secure.

2021-04-30 04:31 UTC, aujjwal-redhat commented on common/rexe.py
>                      hostname=node,
Yeah. Paramiko needs the node IP address in hostname and pkey for privatekey from RSA file. If we want to pass the address directly we would need key_filename.

2021-04-30 11:37 UTC, srijan-sivakumar commented on common/rexe.py
> +            # paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
@aujjwal-redhat does it work without the AutoAddPolicy() ? has this been tested after removing host keys and retrying passwordless ssh ?

2021-04-30 11:38 UTC, srijan-sivakumar commented on common/rexe.py
>                  paramiko.AutoAddPolicy())
@aujjwal-redhat does it work without the AutoAddPolicy() ? has this been tested after removing host keys and retrying passwordless ssh ?

2021-04-30 11:40 UTC, aujjwal-redhat commented on common/rexe.py
>                  paramiko.AutoAddPolicy())
Yeah @srijan-sivakumar , it works without AutoAddPolicy().
If we remove the `load_host_keys` it does not work. The host keys are needed to authenticate.

2021-04-30 11:43 UTC, aujjwal-redhat commented on common/rexe.py
>                  paramiko.AutoAddPolicy())
It will throw this error
```bash
paramiko.ssh_exception.SSHException: Server '10.xx.xx.74' not found in known_hosts
```

2021-04-30 11:46 UTC, srijan-sivakumar commented on common/rexe.py
>                  paramiko.AutoAddPolicy())
cool. I was actually checking about the AutoAddPolicy..anyway we'd be needing the known_hosts data for passwordless ssh to work.

2021-04-30 11:46 UTC, srijan-sivakumar commented
LGTM.

2021-04-30 11:46 UTC, merged

2021-04-30 11:46 UTC, srijan-sivakumar reviewed
LGTM