Added message to handle connection failure
srijan-sivakumar/redant pull request #243
Opened 2021-05-03 10:04 UTC by aujjwal-redhat

Previously, on shutdown or connection failure a stact traceback was
displayed. Instead, a simple message is being displayed in its place
now.

Fixes: #236

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-05-03 10:42 UTC, srijan-sivakumar requested changes

2021-05-03 10:42 UTC, srijan-sivakumar commented on common/rexe.py
> +                print(f"Connection failed on {node}.\nTake a look in the main.log file for more details")
Ahh..No @aujjwal-redhat , We should actually put a connection failure check in the environ class itself. And then stop the framework run. This print statement inside the rexe won't be good. Probably we can have a check as to what type of exception we have and if it related to node being not up or not able to connect to it in the environ's modules itself. But the print here is not the best way to go ahead.

2021-05-03 10:48 UTC, aujjwal-redhat commented on common/rexe.py
> +                print(f"Connection failed on {node}.\nTake a look in the main.log file for more details")
Yeah, that would be better.

2021-05-03 12:11 UTC, aujjwal-redhat commented
```bash
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -rf "/home/MyWork/results.txt" -t tests/functional/glusterd/

            Oops! There was a timeout connecting the servers.
            Message:timed out
            Check and run again.
            
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -rf "/home/MyWork/results.txt" -t tests/functional/glusterd/

            It seems one of the nodes is down. 
            Message: [Errno None] Unable to connect to port 22 on 10.70.43.115.
            Check and run again.
            
```

2021-05-04 06:55 UTC, srijan-sivakumar requested changes

2021-05-04 06:55 UTC, srijan-sivakumar commented on common/rexe.py
> +                    timeout=15,
Good that we have finally got to this thing. This should be a configurable parameter to be handled by the user. We can add a default value to be used if the user doesn't want to provide one. Also is this timeout reflective of connection timeout or even when we execute commands ?

2021-05-04 07:09 UTC, aujjwal-redhat commented on common/rexe.py
> +                    timeout=15,
This is just for connection timeout. So if the server doesn't respond within the timeout, the connection gets terminated.

2021-05-04 07:12 UTC, aujjwal-redhat commented on common/rexe.py
> +                    timeout=15,
> Good that we have finally got to this thing. This should be a configurable parameter to be handled by the user. We can add a default value to be used if the user doesn't want to provide one. Also is this timeout reflective of connection timeout or even when we execute commands ?

Yeah we can do that. Should we provide the option in the config file or in the arguments?

2021-05-04 10:12 UTC, aujjwal-redhat commented on common/rexe.py
> +                    timeout=15,
@srijan-sivakumar I have made the timeout a parameter that we can get from the config and pass it on. The user can configure the timeout now.

2021-05-04 10:49 UTC, srijan-sivakumar commented on common/rexe.py
> +                    timeout=15,
@aujjwal-redhat , yes that would be a good idea. To get it from config and pass it on to here and other places.

2021-05-04 10:58 UTC, aujjwal-redhat commented on common/rexe.py
> +                    timeout=15,
Yeah have added the changes in the prev commit

2021-05-05 12:56 UTC, srijan-sivakumar requested changes

2021-05-05 12:56 UTC, srijan-sivakumar commented on core/environ.py
> +            exit(0)
I might've missed this before..but we shouldn't exit inside the rexe. The exception should be handled inside environ and then we should exit there. Because if we add exit here, then TC framework run would be disrupted. The reason as to why we need these logging is to get details as to what happened. And this being the preliminary check at the very beginning of the framework's run, i.e. inside environ, we can be sure of the nature of the underlying nodes. Also, lets not print here. Just raise exception.

2021-05-05 13:07 UTC, aujjwal-redhat commented on core/environ.py
> +            exit(0)
This isn't inside rexe. It's inside environ. Moreover, we are already raising the exception from the `establish_connection` in rexe. I am not sure but again raising an exception here will be just overdoing exception handling coz the environ.py file is the one taking care of the environment so the exception from the very beginning must be handled there only. Just a suggestion. :)

2021-05-06 02:46 UTC, srijan-sivakumar approved these changes

2021-05-06 02:46 UTC, srijan-sivakumar commented on core/environ.py
> +            exit(0)
Ahh..my bad then. I guess we are good to go then.

2021-05-06 02:48 UTC, srijan-sivakumar commented
@nishith-vihar could you review this flow ? I've resolved the merge conflicts.

2021-05-06 12:48 UTC, merged