Added arbiter option in volume create
srijan-sivakumar/redant pull request #261
Opened 2021-05-06 11:28 UTC by aujjwal-redhat

In volume ops, inside volume create added arbiter option to take care of
arbiter volume types.

Fixes: #260

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-05-06 11:43 UTC, nik-redhat reviewed
Why aren't we using the same volume ops that we have in glusto itself? They have handled all possible corner cases.

2021-05-06 11:43 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +            if "arbiter_count" in conf_hash["arbiter_count"]:
Ig it should be only `conf_hash`?

2021-05-06 11:45 UTC, nik-redhat commented
Also, try adding 1 test case related to the update being done in the ops library, this will help in testing the feature as well.

2021-05-06 11:52 UTC, srijan-sivakumar commented
> Why aren't we using the same volume ops that we have in glusto itself? They have handled all possible corner cases.

The reason being they have a hardcoded mechanism of volume type and the server and bricks to be used which we don't want to do. Coming to the logic as to how the arbiter volume is to be created, yes that can be understood and seen if it can be taken up from glusto.

2021-05-06 11:53 UTC, srijan-sivakumar requested changes

2021-05-06 11:53 UTC, srijan-sivakumar commented on common/ops/gluster_ops/volume_ops.py
> +            if "arbiter_count" in conf_hash["arbiter_count"]:
Yes..it shouldn't be conf_hash["arbiter_count"]

2021-05-06 11:54 UTC, srijan-sivakumar commented
> Also, try adding 1 test case related to the update being done in the ops library, this will help in testing the feature as well.

@aujjwal-redhat , add arb and dist-arb in the test cases wherein we have already mentioned the volume types.

2021-05-06 11:56 UTC, nik-redhat commented
> > Why aren't we using the same volume ops that we have in glusto itself? They have handled all possible corner cases.
> 
> The reason being they have a hardcoded mechanism of volume type and the server and bricks to be used which we don't want to do. Coming to the logic as to how the arbiter volume is to be created, yes that can be understood and seen if it can be taken up from glusto.

I meant the logic only. That would involve less time and hard work and properly cover the corner cases.

2021-05-06 12:11 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
> +            if "arbiter_count" in conf_hash["arbiter_count"]:
Oh yeah. :)

2021-05-06 12:12 UTC, aujjwal-redhat commented
> > Also, try adding 1 test case related to the update being done in the ops library, this will help in testing the feature as well.
> 
> @aujjwal-redhat , add arb and dist-arb in the test cases wherein we have already mentioned the volume types.

Yeah.

2021-05-06 12:12 UTC, aujjwal-redhat commented
> Also, try adding 1 test case related to the update being done in the ops library, this will help in testing the feature as well.

Yeah true

2021-05-06 12:21 UTC, srijan-sivakumar commented
> > > Why aren't we using the same volume ops that we have in glusto itself? They have handled all possible corner cases.
> > 
> > 
> > The reason being they have a hardcoded mechanism of volume type and the server and bricks to be used which we don't want to do. Coming to the logic as to how the arbiter volume is to be created, yes that can be understood and seen if it can be taken up from glusto.
> 
> I meant the logic only. That would involve less time and hard work and properly cover the corner cases.

True, but if one were to look the volume create flow in glusto it is very straightforward as it directly takes values from config, even the brick values which actually isn't attempted here.

2021-05-06 13:06 UTC, aujjwal-redhat commented
@srijan-sivakumar lemme know if it is fine with the test case part

2021-05-06 14:59 UTC, aujjwal-redhat commented
![Screenshot from 2021-05-06 20-22-46](https://user-images.githubusercontent.com/77244483/117320273-b1c33b00-aea9-11eb-99a3-8d62b8a835fb.png)

2021-05-06 17:33 UTC, srijan-sivakumar commented
LGTM. I've tested it. One of the observations I had is that in a 2 GB RAM VM, the concurrency limit has to be set to 2 or else the VMs go for a toss. This is something we have a limitation from glusterfs side. This shows that if I'm developing TCs in one server, heavy TCs will bring down the whole system. Hence we need sanity checks for that. But even before we venture there, we need to understand that there is a limitation on how many volumes can be run in the VMs we have. Had these been bare metal servers, we can increase the concurrency limit. So, if anyone is to try the framework, DO NOT KEEP CONCURRENCY LIMIT AS DEFAULT ON THE GO> REDUCE IT!

2021-05-06 17:33 UTC, srijan-sivakumar approved these changes

2021-05-06 17:33 UTC, merged

2021-05-07 04:46 UTC, aujjwal-redhat commented
> LGTM. I've tested it. One of the observations I had is that in a 2 GB RAM VM, the concurrency limit has to be set to 2 or else the VMs go for a toss. This is something we have a limitation from glusterfs side. This shows that if I'm developing TCs in one server, heavy TCs will bring down the whole system. Hence we need sanity checks for that. But even before we venture there, we need to understand that there is a limitation on how many volumes can be run in the VMs we have. Had these been bare metal servers, we can increase the concurrency limit. So, if anyone is to try the framework, DO NOT KEEP CONCURRENCY LIMIT AS DEFAULT ON THE GO> REDUCE IT!

ACK