PeerOps Modified
srijan-sivakumar/redant pull request #271
Opened 2021-05-07 12:14 UTC by nishith-vihar

when peer probed function is added to wait until peer connects
and function is added to check if peer is connected and few
other functions are modified.

Fixes: #235
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-05-07 12:35 UTC, aujjwal-redhat commented on common/ops/gluster_ops/peer_ops.py
> +    def is_peer_connected(self, node, servers)->bool:
NIT:
node: str
servers : list

2021-05-07 12:35 UTC, aujjwal-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            wait_timeout: timeout to retry connected status check in node.
Same as above.

2021-05-07 12:50 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +    def is_peer_connected(self, node, servers)->bool:
Ack

2021-05-07 12:50 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            wait_timeout: timeout to retry connected status check in node.
Ack

2021-05-07 13:37 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +            'peer'(list|dict): If single peer is present then dict is returned
@nishith-vihar , let's shift these examples into the readme. This would go to the doc/RP/common/ops/peer_ops.md

2021-05-12 08:23 UTC, nik-redhat requested changes

2021-05-12 08:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            node (str): Node from which peer probe has to be executed.
nit: peer status

2021-05-12 08:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            server_ips.append(socket.gethostbyname(server))
Does this guarantee that the servers passed would be hostnames and not IP addresses?

2021-05-12 08:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
This case isn't possible as Gluster would handle the generation of UUID and if that's wrong it would report an error.

2021-05-12 08:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +        return True
Simply returning `is_connected` should do?

2021-05-12 08:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            peer_status_list = [peer_status_list]
If we are ultimately converting the value to a list then why at all pass a dictionary? What benefit does that give?

2021-05-12 08:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
Also, if we do not `break` from the loop here and at line: 265, then the final result might be wrong considering the peer in this iteration is not connected but the next ones are and the end value is `True`, which is wrong.

2021-05-12 08:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +        self.logger.error(f"Peers are not in connected state: {servers}")
This is not needed as the `is_peer_connected` function should log the correct result. But, that too needs to be modified a bit, check the above comment.

2021-05-12 08:23 UTC, nik-redhat commented on core/environ.py
> +            print(error)
Was this added for testing or we actually need it?

2021-05-12 08:31 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +    def peer_probe(self, server: str, node: str) -> dict:
All the ops are following the same format. If it is really not required then we can later raise an issue and take it up in a different patch for all the ops.

2021-05-12 08:32 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
Ack

2021-05-12 08:35 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
>          return ret
I think i have to change that

2021-05-12 08:37 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            node (str): Node from which peer probe has to be executed.
Ack

2021-05-12 08:39 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
Ack

2021-05-12 08:39 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +        return True
Ack

2021-05-12 08:42 UTC, nishith-vihar commented on core/environ.py
> +            print(error)
Yeah. I think it was for testing. Will remove it

2021-05-12 09:04 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            node (str): Node from which peer probe has to be executed.
Ack

2021-05-12 09:06 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +    def peer_probe(self, server: str, node: str) -> dict:
If all the ops are using it then it's fine, though I don't think it helps, because by default python will simply ignore it and just useful for readability. If we actually want to do a check, we will have to use a separate library.

2021-05-12 09:10 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            peer_status_list = [peer_status_list]
actually when the peer status command is executed, if there is only one node then 'dict' is returned when the output is converted to xml format back in the rexe itself. so that is why we convert that to list over here which is only in case of one node scenario. if there are multiple nodes the we return list from get_peer_status command

2021-05-12 09:14 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            server_ips.append(socket.gethostbyname(server))
Yeah. actually it is all IPs. conversion is not required here.

2021-05-12 09:17 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            peer_status_list = [peer_status_list]
So, are you saying it's controlled centrally for all such cases where we return a single value it would be a dictionary?

2021-05-12 09:20 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            peer_status_list = [peer_status_list]
yes

2021-05-12 09:21 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
That is not the case here. Even if the next node is connected, the variable is not made true.

2021-05-12 09:23 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            peer_status_list = [peer_status_list]
Ok, then we can ignore it.

2021-05-12 09:25 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
How?

2021-05-12 09:25 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +        self.logger.error(f"Peers are not in connected state: {servers}")
Ack

2021-05-12 09:26 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
Ohh, yes got it. But, again what's the benefit in continuing with the loop if one of the peers is disconnected?

2021-05-12 09:28 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
just so that we get to know all the servers which are not connected at once rather than connecting the first unconnected server just to realize after running it one more time that another server is not connected.

2021-05-12 09:34 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +                    is_connected = False
Makes sense.

2021-05-12 09:59 UTC, aujjwal-redhat commented on .github/workflows/linting.yml
> +          flake8 $(pwd) --ignore=C901,F811,F841,E722,E226,E402,W503 --count --max-complexity=10 --max-line-length=79 --statistics
Can you add the same to the script :) ?

2021-05-12 09:59 UTC, aujjwal-redhat commented on .github/workflows/linting.yml
> +          flake8 $(pwd) --ignore=C901,F811,F841,E722,E226,E402,W503 --count --max-complexity=10 --max-line-length=79 --statistics
tools/linting.sh

2021-05-12 09:59 UTC, aujjwal-redhat commented on common/ops/gluster_ops/peer_ops.py
> +                        be replaced by corresponding IP.
NIT: return missing in docstring

2021-05-12 10:00 UTC, nik-redhat requested changes

2021-05-12 10:32 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +        self.execute_abstract_op_node(cmd, node)
If the command execution fails here then exception is raised in abstract ops which is caught by parent test. So there will not be any need to check the return status.

2021-05-12 10:33 UTC, nishith-vihar commented on .github/workflows/linting.yml
> +          flake8 $(pwd) --ignore=C901,F811,F841,E722,E226,E402,W503 --count --max-complexity=10 --max-line-length=79 --statistics
Ack

2021-05-12 10:34 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +                        be replaced by corresponding IP.
Ack

2021-05-12 10:37 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +        self.execute_abstract_op_node(cmd, node)
Ack.

2021-05-12 10:41 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
Actually the ip address in the peer status is held by the 'hostname' attribute. so if it has a hostname then it will convert into ip or else it will stay as ip.

2021-05-12 10:51 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
Ohh, that doesn't matter. It will contain the value that you will supply while peer probing, if you peer probe using IP address then that `hostname` field would have the IP address only.

2021-05-12 11:00 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
No. I think sometimes even if we give ip address and if it has a hostname it displays the hostname for the peer status command. for example the below is the output of my peer status:
`Hostname: dhcp42-209.lab.eng.blr.redhat.com
Uuid: 504fdf87-805a-4e8f-a266-b2f45d76958a
State: Peer in Cluster (Disconnected)`
even though i have never given 'dhcp42-209.lab.eng.blr.redhat.com' while probing.

2021-05-12 11:10 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
Actually, that depends upon the `/etc/hosts` file of the system. Suppose I change the reference to use the IP name in both the place it will work fine.

2021-05-12 11:13 UTC, nishith-vihar commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
Got it. So now basically the change to make is from `socket.gethostbyname(peer_stat['hostname'])` to `peer_stat['hostname']` right?

2021-05-12 11:17 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
Ok..just to add a point here.. we can do the changes in the /etc/hosts, but @nik-redhat , lets not leave it to the user. If we can handle it in here, it is better to do so

2021-05-12 11:18 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
Yes, for this code.
But at the VMs level, we still need to see how the hosts are configured so that we get the correct value.

2021-05-12 11:22 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
I have experimented with this part and it turns into failure many a times and we don't want to hear the same complaints which people usually tag with Glusto, if we are taking the hostname, and that too only when we don't have the ip as response. Now even in this scenario, the tests can fail if the user has added hostname in his /etc/hosts and that won't be available when another node tries to find its resolution with the DNS. Now that is a configuration user will have to guard properly. So, either way, the user would have to add the hostname to the /etc/hosts, they cannot have it one way and only in one server. So, we can enforce one edict that don't add custom names to the servers in /etc/hosts then with the current code, even if we were to get hostname that will be a FQDN.

2021-05-12 11:22 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
I know, but I am not sure if this function could increase the time consumption as well. Since we are doing it for each server, and suppose in a test case we are doing a status check multiple times.

2021-05-12 11:23 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
So, my proposal is an enforcement..I mean you cannot have the cake and eat it too :p, plus one server config missed or wrong config added in /etc/hosts can wreck havoc for our flow.

2021-05-12 11:26 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
> > Ok..just to add a point here.. we can do the changes in the /etc/hosts, but @nik-redhat , lets not leave it to the user. If we can handle it in here, it is better to do so
> 
> I know, but I am not sure if this function could increase the time consumption as well. Since we are doing it for each server, and suppose in a test case we are doing a status check multiple times.

This would be a micro improvement. Also non-disruptive test cases would not be re-peering most of the times. The disruptive cases might do that, and even in those scenarios, I'm trying to come up with a way to handle complete re-peering from scratch. So I don't think a single call to the local DNS/switch for FQDN resolutions will cause much issue.

2021-05-12 11:32 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +            if (socket.gethostbyname(peer_stat['hostname']) in servers
Okay, then I would leave it to this :slightly_smiling_face:

2021-05-12 11:34 UTC, nik-redhat approved these changes

2021-05-12 11:34 UTC, merged