[Test] test_glusterd_quorum_command migration
srijan-sivakumar/redant pull request #312
Opened 2021-05-11 17:20 UTC by srijan-sivakumar

Glusto test link : [test_glusterd_quorum_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_quorum_command.py)

Fixes: #308

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

2021-05-11 17:34 UTC, nik-redhat requested changes

2021-05-11 17:34 UTC, nik-redhat commented on tests/functional/glusterd/test_glusterd_quorum_command.py
> +    """ Testing Quorum CLI commands in GlusterD """
Considering we have already added a description above, this is not needed.

2021-05-11 17:34 UTC, nik-redhat commented on tests/functional/glusterd/test_glusterd_quorum_command.py
> +            vol = self.vol_name
Instead of this....by looking at the usage I think the volume name can be passed directly as the arg.

2021-05-12 04:02 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_glusterd_quorum_command.py
> +    """ Testing Quorum CLI commands in GlusterD """
Ack.

2021-05-12 04:21 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_glusterd_quorum_command.py
> +            vol = self.vol_name
Currently, I have added this as a class method here, but technically this method should exist inside the vol_ops. Coming to the part of providing the volname. Yes, now that I think we need to provide it.

2021-05-12 05:06 UTC, aujjwal-redhat approved these changes
LGTM

2021-05-12 05:10 UTC, nik-redhat approved these changes

2021-05-12 05:10 UTC, merged