Added test_glusterd_friend_updates_on_node_rejoin
srijan-sivakumar/redant pull request #330
Opened 2021-05-12 14:16 UTC by nik-redhat

Description:

Migrated the [test-case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py)

Updates: #292 
Fixes: #316 

Signed-off-by: nik-redhat <nladha@redhat.com>

2021-05-12 14:18 UTC, nik-redhat commented
Can anyone verify if the test migrated is running fine or not? I don't have the setup to check :p

2021-05-12 14:35 UTC, aujjwal-redhat requested changes

2021-05-12 14:35 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +        redant.looger.info("Expected: No friend updates between other"
It will be logger :)

2021-05-12 14:35 UTC, aujjwal-redhat commented
> Can anyone please verify if the test migrated is running fine or not? I don't have the setup to check :p

Yeah, I can test that. :)

2021-05-12 14:41 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +
Moreover we need to put his as docstring as test_list_builder will fail

2021-05-12 14:52 UTC, nik-redhat commented
> > Can anyone please verify if the test migrated is running fine or not? I don't have the setup to check :p
> 
> Yeah, I can test that. :)

Thank you @aujjwal-redhat . I have updated the code, could you please share your results here after running the test.

2021-05-14 07:21 UTC, aujjwal-redhat reviewed
Rebase and remove the conflicts :)
Everything LGTM

2021-05-14 08:10 UTC, nik-redhat commented
Done.

2021-05-14 08:16 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +"""
NIT: Description :)

2021-05-14 08:19 UTC, nik-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +"""
Ohh, I didn't add that as it was not there in the previous TC, but let's keep things consistent now. Will update it.

2021-05-14 08:21 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +"""
Ack.

2021-05-14 09:27 UTC, aujjwal-redhat approved these changes
LGTM. Thanks for the docstrings' indent :)

2021-05-14 09:30 UTC, nik-redhat commented
@aujjwal-redhat could you please add an ss for this test as well? Thanks in advance.

2021-05-14 11:01 UTC, nishith-vihar commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +        ret = redant.execute_command(cmd, self.server_list[0])
I think we need to add execute_abstract_op_node instead of execute_command so that it raises exception if command fails and if it succeeds it returns ret and the execution can be continued

2021-05-14 11:04 UTC, nishith-vihar commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +                           % (curr_time, uuid))
nit: the formatting of string should be in this manner: f"awk '/{curr_time}/,0' " as is followed in redant. :)

2021-05-14 11:04 UTC, nishith-vihar commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +               "| grep '_handle_friend_update' | wc -l" % curr_time)
same as above

2021-05-14 11:35 UTC, nik-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +        ret = redant.execute_command(cmd, self.server_list[0])
Replacement is needed. But, the execution won't stop even now, since we are ultimately handling the exception in the parent_test_runner.

2021-05-14 13:28 UTC, nishith-vihar approved these changes
LGTM

2021-05-14 13:42 UTC, aujjwal-redhat commented
I am checking the the test case execution in my env. Will update :)

2021-05-14 13:53 UTC, aujjwal-redhat requested changes

2021-05-14 13:53 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +        cmd = (f"awk '/{curr_time}/,0' /var/log/glusterfs/glusterd.log "
WE can use the `glusterd_log_path` variable here also. :)

2021-05-14 13:53 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +        count = int(ret['msg'][0])
ret['msg'] is ['4\n']. In that case ret['msg'][0] will be 4\n. And hence, it will raise the exception.  Make it ret['msg'][0][:-1].

2021-05-14 13:53 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
> +                    if int(ret['msg'][0]) != 0:
same as below

2021-05-14 13:55 UTC, aujjwal-redhat commented
@nik-redhat I made the changes locally and ran the code:
![Screenshot from 2021-05-14 19-24-58](https://user-images.githubusercontent.com/77244483/118280762-20c41380-b4ea-11eb-9128-1fbdba755a1d.png)
It's working :)

2021-05-14 14:09 UTC, aujjwal-redhat approved these changes
LGTM
![Screenshot from 2021-05-14 19-39-10](https://user-images.githubusercontent.com/77244483/118282645-20c51300-b4ec-11eb-81dc-d09f7b0c4b53.png)

2021-05-14 14:11 UTC, merged