Fixed wait_for_glusterd issues
srijan-sivakumar/redant pull request #332
Opened 2021-05-12 16:04 UTC by aujjwal-redhat

* Removed the condition to explicitly convert node to list
* Changed the condition to return True if ret is 1.

Fixes: #331

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-05-12 16:13 UTC, nik-redhat requested changes

2021-05-12 16:13 UTC, nik-redhat commented on common/ops/gluster_ops/gluster_ops.py
>              return False
Doesn't make sense to check this. Otherwise, we would be checking this in all the OPs functions.

2021-05-12 16:13 UTC, nik-redhat commented on common/ops/gluster_ops/gluster_ops.py
> +            if ret:
It should be `if ret==1`, else it will pass of `-1` too.

2021-05-14 05:30 UTC, aujjwal-redhat commented on common/ops/gluster_ops/gluster_ops.py
>              return False
Ack

2021-05-14 05:30 UTC, aujjwal-redhat commented on common/ops/gluster_ops/gluster_ops.py
> +            if ret:
Ack

2021-05-14 05:42 UTC, nik-redhat approved these changes

2021-05-14 05:42 UTC, merged