Migration of test_gluster_volume_status_xml_dump
srijan-sivakumar/redant pull request #338
Opened 2021-05-14 05:03 UTC by nishith-vihar

[test_gluster_volume_status_xml_dump.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_gluster_volume_status_xml_dump.py) test case is migrated to redant.

Updates: #292
Fixes: #335 
Signed-off-by: Nishith Vihar Sakinala nsakinal@redhat.com

2021-05-14 06:51 UTC, nik-redhat requested changes
Also, the test requires testing it with 2 or more volumes, so create and start another volume in the test itself, then stop the initially created volume and check the status dump. Delete the intermediate volume in the end.

2021-05-14 06:51 UTC, nik-redhat commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +        Setps:
nit: Steps

2021-05-14 06:51 UTC, nik-redhat commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +    Test Default volume behavior and quorum options
I don't think we are checking any quorum options, this can be updated.

2021-05-14 06:58 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +            self.assertEqual(out1, out)
I don't remember seeing assertEqual function in out codebase..can you point out as to where we have defined this ?

2021-05-14 07:10 UTC, nishith-vihar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +        Setps:
Ack

2021-05-14 07:11 UTC, nishith-vihar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +            self.assertEqual(out1, out)
Thats a mistake. it was in glusto. Will remove it

2021-05-14 07:11 UTC, nishith-vihar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +    Test Default volume behavior and quorum options
Ack

2021-05-14 07:39 UTC, nishith-vihar commented
> Also, the test requires testing it with 2 or more volumes, so create and start another volume in the test itself, then stop the initially created volume and check the status dump. Delete the intermediate volume in the end.

any specific volume type to be created or any vol type can be created?

2021-05-14 07:43 UTC, nik-redhat commented
> > Also, the test requires testing it with 2 or more volumes, so create and start another volume in the test itself, then stop the initially created volume and check the status dump. Delete the intermediate volume in the end.
> 
> any specific volume type to be created or any vol type can be created?

Anything, for simplicity, let's keep it a distributed volume with 2/3 bricks.

2021-05-14 08:12 UTC, nik-redhat commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +            redant.logger.error("Failed to get volume status on "
It should raise an exception instead.

2021-05-14 08:12 UTC, nik-redhat commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +                redant.logger.error("Failed to get volume status on "
Same as above.

2021-05-14 13:33 UTC, nishith-vihar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +            redant.logger.error("Failed to get volume status on "
Ack

2021-05-14 13:33 UTC, nishith-vihar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +                redant.logger.error("Failed to get volume status on "
Ack

2021-05-18 02:42 UTC, srijan-sivakumar requested changes

2021-05-18 02:42 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +        Setps:
nit is still active :p Let's not resolve it before either fixing it or adding a relevant response.

2021-05-18 02:43 UTC, srijan-sivakumar commented
@nishith-vihar for best practice, don't resolve the conversations until and unless either,
1. You've changed the code after discussion.
2. Provided some explanation as to why the said suggestion is not taken up.

2021-05-19 08:16 UTC, nishith-vihar commented
![Screenshot from 2021-05-19 13-43-04](https://user-images.githubusercontent.com/77044911/118779360-947a6d80-b8a8-11eb-82fa-ad3ce5563939.png)

2021-05-19 08:23 UTC, nik-redhat commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +        redant.volume_delete(volume_name1, self.server_list[0])
In the future, the addition of the `volume_cleanup` function for these kind of tests would be helpful.

2021-05-19 08:23 UTC, nik-redhat approved these changes

2021-05-19 08:28 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
> +        redant.volume_delete(volume_name1, self.server_list[0])
Ack.

2021-05-19 08:30 UTC, srijan-sivakumar approved these changes
LGTM

2021-05-19 08:30 UTC, merged