Migrated test_ops_when_one_node_is_down
srijan-sivakumar/redant pull request #350
Opened 2021-05-14 13:32 UTC by aujjwal-redhat

Added the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_ops_when_one_node_is_down.py).
Made modifications as per the ops.

Updates: #292

Fixes: #348

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-05-14 15:39 UTC, nik-redhat requested changes

2021-05-14 15:39 UTC, nik-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +"""
ig you forgot to remove this :p

2021-05-14 15:39 UTC, nik-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +            redant.wait_for_glusterd_to_start(server)
Here, a check for the `ret` value is needed. And, raise an exception if it is false.

2021-05-14 15:39 UTC, nik-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +                                         self.server_list)
Same as above

2021-05-14 15:58 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +            redant.wait_for_glusterd_to_start(server)
Ack

2021-05-14 15:59 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +"""
XD Oops

2021-05-14 16:22 UTC, nik-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +                raise Exception("Failed: wait for glusterd to start")
The error should instead say: `Glusterd not started on {server}`

2021-05-14 16:23 UTC, nik-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +            raise Exception("Failed : Wait for peers to connect")
Reformat the error msg as `All the peers are not connected`.

2021-05-18 05:02 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +                raise Exception("Failed: wait for glusterd to start")
Ack.
Sorry for the delayed response. :)

2021-05-18 05:02 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +            raise Exception("Failed : Wait for peers to connect")
Ack

2021-05-18 05:12 UTC, aujjwal-redhat commented
![Screenshot from 2021-05-18 10-41-42](https://user-images.githubusercontent.com/77244483/118593712-c8c92d80-b7c5-11eb-9df1-050cdcee50f9.png)

2021-05-18 07:52 UTC, nik-redhat requested changes

2021-05-18 07:52 UTC, nik-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +class TestOpsWhenOneNodeIsDown(AbstractTest):
It needs to be updated based on the latest update on the master branch for the test execution patterns.

2021-05-18 08:19 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_ops_when_one_node_is_down.py
> +class TestOpsWhenOneNodeIsDown(AbstractTest):
Ack

2021-05-18 08:26 UTC, aujjwal-redhat commented
![Screenshot from 2021-05-18 13-55-52](https://user-images.githubusercontent.com/77244483/118617987-ca541f00-b7e0-11eb-9f83-476e6709b8e1.png)

2021-05-19 08:06 UTC, aujjwal-redhat commented
@nik-redhat @srijan-sivakumar @nishith-vihar can you guys review this one as well? :)

2021-05-19 08:21 UTC, nik-redhat approved these changes

2021-05-19 08:21 UTC, merged