Added documentation for BP volume ops
srijan-sivakumar/redant pull request #406
Opened 2021-05-20 14:07 UTC by nishith-vihar

Added documentation for BP volume ops

Fixes: #394
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-05-21 04:34 UTC, aujjwal-redhat requested changes

2021-05-21 04:34 UTC, aujjwal-redhat commented on docs/BP/Ops/volume_ops.md
> +Volume Ops contains all the functions required to carry out the volume related operatins. Given below are all the details about all the functions implemented in the Volume Ops library:
operatins => operations

2021-05-21 07:54 UTC, nishith-vihar commented on docs/BP/Ops/volume_ops.md
> +Volume Ops contains all the functions required to carry out the volume related operatins. Given below are all the details about all the functions implemented in the Volume Ops library:
Ack

2021-05-24 06:02 UTC, nik-redhat commented on docs/BP/Ops/volume_ops.md
> +1) [**volume_mount**](https://github.com/srijan-sivakumar/redant/blob/d95bd1a1da8d16131bedf37f8d2ebf8f5c3259f9/common/ops/gluster_ops/volume_ops.py#L16)<br>
Better to use the relative path here and all other places below.

2021-05-24 06:03 UTC, nik-redhat commented on docs/BP/Ops/volume_ops.md
> +1) [**volume_mount**](https://github.com/srijan-sivakumar/redant/blob/d95bd1a1da8d16131bedf37f8d2ebf8f5c3259f9/common/ops/gluster_ops/volume_ops.py#L16)<br>
And in other docs as well.

2021-05-24 06:16 UTC, nishith-vihar commented on docs/BP/Ops/volume_ops.md
> +1) [**volume_mount**](https://github.com/srijan-sivakumar/redant/blob/d95bd1a1da8d16131bedf37f8d2ebf8f5c3259f9/common/ops/gluster_ops/volume_ops.py#L16)<br>
I am not sure if we can use relative paths to point to a particular 'line' in a file.

2021-05-24 06:25 UTC, nik-redhat commented on docs/BP/Ops/volume_ops.md
> +1) [**volume_mount**](https://github.com/srijan-sivakumar/redant/blob/d95bd1a1da8d16131bedf37f8d2ebf8f5c3259f9/common/ops/gluster_ops/volume_ops.py#L16)<br>
Why? Have you tried?

2021-05-24 06:42 UTC, nishith-vihar commented on docs/BP/Ops/volume_ops.md
> +1) [**volume_mount**](https://github.com/srijan-sivakumar/redant/blob/d95bd1a1da8d16131bedf37f8d2ebf8f5c3259f9/common/ops/gluster_ops/volume_ops.py#L16)<br>
My bad. I got how to do that. I will make the changes

2021-05-24 07:40 UTC, srijan-sivakumar approved these changes

2021-05-24 11:01 UTC, merged