[Doc] Adding documentation for Rexe functions
srijan-sivakumar/redant pull request #407
Opened 2021-05-20 15:03 UTC by srijan-sivakumar

Fixes: #392

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

2021-05-20 15:04 UTC, srijan-sivakumar commented
To add abstract execute function details.

2021-05-24 04:53 UTC, aujjwal-redhat requested changes

2021-05-24 04:53 UTC, aujjwal-redhat commented on docs/BP/Ops/rexe.md
> +operations ? Well, because the remote execution opeations can be performed
opeations => operations

2021-05-24 04:53 UTC, aujjwal-redhat commented on docs/BP/Ops/rexe.md
> +-> Whether we use is inside an ops or directly in a test case ( in case of
is => it

2021-05-24 04:53 UTC, aujjwal-redhat commented on docs/BP/Ops/rexe.md
> +-> Whether we use is inside an ops or directly in a test case ( in case of
is =>it

2021-05-24 04:53 UTC, aujjwal-redhat commented on docs/BP/Ops/rexe.md
> +-> Whether we use is inside an ops or directly in a test case ( in case of
is => it

2021-05-24 04:53 UTC, aujjwal-redhat commented on docs/BP/Ops/rexe.md
> +-> Whether we use is inside an ops or directly in a test case ( in case of a
is => it

2021-05-24 04:53 UTC, aujjwal-redhat commented on docs/BP/Ops/rexe.md
> +-> Whether we use is inside an ops or directly in a test case ( in case of a
is => it

2021-05-24 05:00 UTC, nishith-vihar commented on docs/BP/Ops/opsIndex.md
> +4. [Profile Ops](./peer_ops.md)
I think this should be profile_ops.md

2021-05-24 05:29 UTC, aujjwal-redhat approved these changes
LGTM

2021-05-24 05:34 UTC, nishith-vihar approved these changes
LGTM

2021-05-24 05:40 UTC, merged