Migrated test_peer_probe_firewall_ports_not_opened
srijan-sivakumar/redant pull request #443
Opened 2021-05-25 12:03 UTC by neesingh-rh

Migrated test_peer_probe_firewall_ports_not_opened.
core file verification is yet to be done
after the addition of is_core_file_created.

Fixes: #429

2021-05-26 06:46 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_profile_operations_with_one_node_down.py
> +#  Copyright (C) 2019-2020  Red Hat, Inc. <http://www.redhat.com>
@neesingh-rh why are we taking this test file...Is this going to be taken along with the above test case in this patch itself ?

2021-05-26 11:37 UTC, neesingh-rh commented on tests/functional/glusterd/test_profile_operations_with_one_node_down.py
> +#  Copyright (C) 2019-2020  Red Hat, Inc. <http://www.redhat.com>
No,it was by mistake

2021-05-31 12:09 UTC, neesingh-rh commented
test_peer_probe_firewall_ports_not_opened-Generic PASS

Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_peer_probe_firewall_ports_not_opened
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   Generic   |     PASS    | 21.468557834625244 |
+-------------+-------------+--------------------+



Framework runtime : 26.572521209716797

2021-05-31 12:34 UTC, neesingh-rh commented
x-special/nautilus-clipboard
copy
file:///home/neerajpsingh/Pictures/peer_probe_firewall.png

2021-05-31 12:35 UTC, neesingh-rh commented
![image](https://user-images.githubusercontent.com/79842675/120194054-baa1f500-c23a-11eb-9793-48b4d61977e8.png)

2021-05-31 12:57 UTC, srijan-sivakumar requested changes

2021-05-31 12:57 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
> +        for server in self.server_list[1:]:
we can use the destroy_cluster function here instead. This logic is handled inside it.

2021-05-31 14:12 UTC, nik-redhat requested changes

2021-05-31 14:12 UTC, nik-redhat commented on tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
> +            redant.execute_abstract_op_node(cmd, server)
There isn't any restart in the glusto TC, any specific reasons for adding this?

2021-05-31 14:12 UTC, nik-redhat commented on tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
> +            redant.logger.info(msg)
Also, you need to verify the `error_msg` from the command execution as per the glusto TC. You can use the `excep` arg to pass `False` to it and get the complete ret value from the command execution.

2021-05-31 14:12 UTC, nik-redhat commented on tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
> +            raise Exception("Core file is found")
The TC asks to check `ERROR` logs in the `glusterd.log` file before checking for the core file. Please update.

2021-05-31 14:12 UTC, nik-redhat commented on tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
> +        self._add_firewall_service(redant)
This call and function can be removed and instead use the code in the terminate function, as mentioned above.

2021-06-05 05:35 UTC, nik-redhat commented
Closing this PR, I will send out a separate PR for the TC.

2021-06-05 05:35 UTC, closed without merging