Added check_core_file_exists
srijan-sivakumar/redant pull request #456
Opened 2021-05-26 06:06 UTC by aujjwal-redhat

Added the function check_core_file_exists.

Fixes: #359

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-05-27 11:07 UTC, srijan-sivakumar commented on .pylintrc
> +        R0915,
What are these error codes in linting ?

2021-05-27 11:12 UTC, nik-redhat requested changes

2021-05-27 12:16 UTC, aujjwal-redhat commented on .pylintrc
> +        R0915,
W0102 was added because it threw error for the following line:
```js
paths=['/', '/var/log/core',  '/tmp', '/var/crash', '~/']
```
Saying multiple values in list as default value which is not specifically an error but a requirement in our case

2021-05-27 12:17 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +                logfiles = ret['msg'][0].rstrip("\n")
yeah will push the recent changes

2021-05-27 12:17 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +                    out = ret['msg'][0].rstrip("\n")
ack

2021-05-27 12:17 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +                    print(f"out, ret['msg']: {ret['msg']}")
Yeah : )

2021-05-27 12:17 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +                            file_timestamp = ret['msg'][0].rstrip('\n')
ack

2021-05-27 12:18 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +            return False
True

2021-05-27 12:18 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +        need to pass path from test method
Ack.

2021-05-27 14:26 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +                            file_timestamp = ret['msg'][0].rstrip('\n')
Hey @nik-redhat , this will be a single value right? It tells last modification time.

2021-05-27 16:53 UTC, srijan-sivakumar commented on .pylintrc
> +        R0915,
cool

2021-05-28 03:34 UTC, srijan-sivakumar approved these changes
LGTM. Ran the test case. No issues found in CI.

2021-05-28 03:35 UTC, merged