Migrated test_reserved_port_range_for_gluster
srijan-sivakumar/redant pull request #458
Opened 2021-05-26 10:39 UTC by aujjwal-redhat

Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_reserved_port_range_for_gluster.py)

Fixes: #410

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-05-26 15:10 UTC, aujjwal-redhat commented
@nik-redhat @srijan-sivakumar In this test case, 50 volumes are created but only 24 are able to start. It fails for 25th volume with the message `Commit failed on localhost. Please check log file for details.`

It is running perfectly for 25 volume scenario but not fully for 50 volumes.

2021-05-26 15:33 UTC, nik-redhat commented
You can use this script:
```
for i in {1..75}
do
    gluster vol create vol$i <brick-list>
    sleep 1
    gluster vol start vol$i
done
```

2021-05-26 15:40 UTC, aujjwal-redhat commented
> > @nik-redhat @srijan-sivakumar In this test case, 50 volumes are created but only 24 are able to start. It fails for 25th volume with the message `Commit failed on localhost. Please check log file for details.`
> > It is running perfectly for 25 volume scenario but not fully for 50 volumes.
> 
> Try creating 50 volumes in that setup, using a bash script. Without the framework. I think it's a memory issue.

50 volumes are getting created but start is failing.

2021-05-26 15:42 UTC, nik-redhat commented
Using, bash as well?

2021-05-26 15:42 UTC, aujjwal-redhat commented
> You can use this script:
> 
> ```
> for i in {1..75}
> do
>     gluster vol create vol$i <brick-list>
>     sleep 1
>     gluster vol start vol$i
> done
> ```

yeah will have to try something like this

2021-05-26 15:42 UTC, aujjwal-redhat commented
> Using, bash as well?

Ahh.. no just from the framework.

50 vol gets created, start goes up till 24 and then commit fails and deletes the 50 vols

2021-05-26 15:44 UTC, nik-redhat commented
Try from bash, I think you will get the same result or at max 1-5 volumes extra.

2021-05-26 16:08 UTC, srijan-sivakumar commented
I think it is the memory and the env issue. Gluster is not meant for creating 50 volumes in 3 VMs that too very light weight VMs.

2021-05-26 16:09 UTC, srijan-sivakumar commented
Such a test case cannot be run in the VMs we are using. ( Also a customer should be sane enough to not to try such things in a small resource constrained VM ) Technically it is not even a recommended operation.

2021-06-03 05:33 UTC, srijan-sivakumar requested changes

2021-06-03 05:33 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                   "/usr/local/etc/glusterfs/glusterd.vol")
the path has to be changed to `/etc/glusterfs/glusterd.vol`

2021-06-03 05:33 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                   "/usr/local/etc/glusterfs/glusterd.vol")
path has to be changes to `/etc/glusterfs/glusterd.vol`

2021-06-03 05:33 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                   "/usr/local/etc/glusterfs/glusterd.vol")
same path change.

2021-06-03 05:35 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                   "/usr/local/etc/glusterfs/glusterd.vol")
Ack

2021-06-03 05:35 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                   "/usr/local/etc/glusterfs/glusterd.vol")
Ack

2021-06-03 05:35 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                   "/usr/local/etc/glusterfs/glusterd.vol")
Ack

2021-06-03 05:53 UTC, srijan-sivakumar requested changes

2021-06-03 05:53 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +            sleep(2)
Also.instead of sleep let's use wait_for_glusterd_to_start function...

2021-06-03 05:53 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +
call the wait_for_glusterd_to_start here also.

2021-06-03 05:54 UTC, srijan-sivakumar requested changes

2021-06-03 05:54 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +        try:
Also..we don't need try-except over the whole test...we can remove that.

2021-06-03 06:08 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +            sleep(2)
Ack

2021-06-03 06:09 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +
Ack

2021-06-03 06:09 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +        try:
Yeah, that was while testing. Will remove it.

2021-06-03 06:21 UTC, srijan-sivakumar requested changes

2021-06-03 06:21 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +        self.port_range_changed = True
nit: Do put a variable definition above the command execution on line 56. `self.port_range_changed = False`. The reason ? => Well if the execute_abstract_op_node command failed, we will go to terminate and as `self.port_range_changed` has not yet been declared, it will throw an exception. So let's just add the initial value as false and put it on line 56, before the command execution.

2021-06-03 06:24 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +        self.port_range_changed = True
Ack

2021-06-03 07:20 UTC, srijan-sivakumar approved these changes
LGTM

2021-06-03 07:20 UTC, merged

2021-06-03 07:36 UTC, nik-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                                 self.server_list, self.brick_roots, True)
Why is volume created with `force`?

2021-06-03 07:38 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                                 self.server_list, self.brick_roots, True)
Actually the default volume creation itself is force if you remember in the CI env.. :p

2021-06-03 07:39 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                                 self.server_list, self.brick_roots, True)
Also..I think it is volume start which is to fail..in this test case..so would volume creation with force affect that ? ( Technically the volume 50 isn't created as ports have been exhausted )

2021-06-03 07:41 UTC, nik-redhat commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                                 self.server_list, self.brick_roots, True)
Volume create would succeed with the port restriction, but the start would fail.
Yes, I remember the CI limitation, but let's not have the same being done in the TC, the test doesn't require the volume to be created with force. So, that when we fix the CI and do not do force create by default the TC actually works as expected.

2021-06-03 07:49 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserved_port_range_for_gluster.py
> +                                 self.server_list, self.brick_roots, True)
Cool..then we can remove the force in this case...