Migrated TC test_volume_set_with_quorum_enabled
srijan-sivakumar/redant pull request #461
Opened 2021-05-26 12:24 UTC by nik-redhat

Migrated the TC [test_volume_set_with_quorum_enabled](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_set_with_quorum_enabled.py)

Fixes: #457 
Updates: #292

Signed-off-by: nik-redhat <nladha@redhat.com>

2021-05-26 12:24 UTC, nik-redhat commented
@nishith-vihar @aujjwal-redhat could one of you please verify the TC for me? Thanks in advance :)

2021-05-26 12:39 UTC, aujjwal-redhat commented
I have a 2 server setup so it is failing for line 90:

```js
[2021-05-26 18:01:36,433] ERROR  - Traceback (most recent call last):
  File "./tests/d_parent_test.py", line 79, in parent_run_test
    self.run_test(self.redant)
  File "./tests/functional/glusterd/test_volume_set_with_quorum_enabled.py", line 90, in run_test
    choice(self.new_servers))
  File "/usr/lib64/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

2021-05-26 12:41 UTC, nik-redhat commented
> I have a 2 server setup so it is failing for line 90:
> 
> ```js
> [2021-05-26 18:01:36,433] ERROR  - Traceback (most recent call last):
>   File "./tests/d_parent_test.py", line 79, in parent_run_test
>     self.run_test(self.redant)
>   File "./tests/functional/glusterd/test_volume_set_with_quorum_enabled.py", line 90, in run_test
>     choice(self.new_servers))
>   File "/usr/lib64/python3.8/random.py", line 290, in choice
>     raise IndexError('Cannot choose from an empty sequence') from None
> IndexError: Cannot choose from an empty sequence
> ```

Yeah, for 2 server setup it will fail. That's the reason I asked you guys😂.....but you also have 2 server setup.... @nishith-vihar what about you?

2021-05-27 10:55 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +        else:
Won't the `servers` already be `servers[:]` by default if it is a list ?

2021-05-27 10:57 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +        if self.glusterd_stopped:
We can simply use `start_glusterd` check here as it will handle check of whether glusterd is started or not.

2021-05-27 10:59 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +        self.glusterd_stopped = False
we won't need this if we change the `terminate` to use just the function `start_glusterd` and `wait_for_glusterd_to_start`

2021-05-27 11:06 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +        self.glusterd_stopped = False
Yup this needs to be discussed based on the last discussion :p

2021-05-27 11:06 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +        if self.glusterd_stopped:
Yes, will update.

2021-05-27 11:08 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +        else:
So, here's the issue I was talking about in the Gchat. If we don't do this, the `servers` variable will still hold the reference of the actual `self.sever_list` variable, but doing so will create a copy. And, later on in this function when we do a `remove()` operation from the `servers` list, it will not affect the actual list.

2021-05-27 11:18 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +        else:
The curse of pass by reference in python for lists.

2021-05-27 11:19 UTC, srijan-sivakumar commented on common/ops/gluster_ops/peer_ops.py
> +        else:
Now this implies, we need to verify if same behavior is seen across code. We use lists extensively!!!!

2021-05-27 11:21 UTC, nik-redhat commented on common/ops/gluster_ops/peer_ops.py
> +        else:
Yup, that's the reason for repeatedly saying that do migration after understanding the code and the logic properly :p

2021-05-27 12:19 UTC, nik-redhat commented
Test Output:
```
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_volume_set_with_quorum_enabled
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 28.000867128372192 |
|     rep     |     PASS    | 27.15277123451233  |
|     disp    |     PASS    | 27.429646492004395 |
|   dist-rep  |     PASS    | 36.59606647491455  |
|  dist-disp  |     PASS    | 35.525830030441284 |
+-------------+-------------+--------------------+



Framework runtime : 157.59987115859985
```

2021-05-27 14:15 UTC, aujjwal-redhat requested changes

2021-05-27 14:15 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +            sleep(5)
nit: can we make it to 2 as well as above it is fine with sleep(2). Just a suggestion : )

2021-05-27 14:15 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +        ret = redant.set_volume_options(self.vol_name,
we don't need ret

2021-05-27 14:15 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +        ret = redant.start_glusterd(self.node_on_glusterd_to_stop)
same as above

2021-05-27 14:15 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +            ret = redant.set_volume_options(self.vol_name,
same as above

2021-05-27 14:15 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
> +        ret = redant.stop_glusterd(self.node_on_glusterd_to_stop)
same as above

2021-05-27 16:05 UTC, nik-redhat commented
Test Output:
```
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_volume_set_with_quorum_enabled
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 27.004956483840942 |
|     rep     |     PASS    |  28.3099684715271  |
|     disp    |     PASS    | 27.43705654144287  |
|   dist-rep  |     PASS    | 36.79739165306091  |
|  dist-disp  |     PASS    | 37.26291608810425  |
+-------------+-------------+--------------------+



Framework runtime : 159.55572295188904
```

2021-05-27 16:17 UTC, aujjwal-redhat approved these changes
LGTM

2021-05-27 16:37 UTC, merged