Migration of test_volume_status_with_absent_bricks
srijan-sivakumar/redant pull request #466
Opened 2021-05-26 19:52 UTC by neesingh-rh

Migrated [test case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_status_with_absent_bricks.py)

Updates: #465 

Signed-off-by: Neeraj Pratap Singh<neesingh@redhat.com>

2021-05-27 08:13 UTC, nik-redhat requested changes

2021-05-27 08:13 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        redant.volume_stop(self.vol_name, self.server_list[0])
The above operations need to be done, with volume stopped. Check the setup part of the glusto TC.
So, we won't be needing a volume_stop here.

2021-05-27 08:13 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        cmd = f"gluster volume start {self.vol_name}"
Use the volume_start function.

2021-05-27 08:13 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        ret = redant.execute_command(cmd, self.server_list[0])
USe abstract function. The `excep` param needs to be added in the `volume_start` function as well. For example, check implementation of `volume_unmount` function.

2021-05-27 08:13 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +            raise Exception("Unexpected!!")
What is `Unexpected!!`?

2021-05-27 08:13 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +            redant.logger.info("Volume hasn't started hence no status for it.")
Why are you doing the same operation twice?

2021-05-27 08:13 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +            raise Exception("Volume status erraneous")
Check the error message from glusto TC, use the same one.

2021-05-27 11:13 UTC, srijan-sivakumar requested changes

2021-05-27 11:13 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        redant.logger.info("Fetch all the bricks of the volume")
We can remove this log. I don't think this is needed.

2021-05-27 11:13 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        brick_list = redant.es.get_brickdata(self.vol_name)
The data structure will be containing the bricks to be provided, in glusto the approach used to obtain the bricks is to query the servers which isn't being done here. Hence we can remove the check for it and also raising the exception.

2021-05-27 11:13 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        redant.logger.info("Brick directory removed successfully")
We don't need the success log.

2021-05-27 11:13 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        redant.volume_stop(self.vol_name, self.server_list[0])
Yes, we need to stop the volume at the very beginning itself.

2021-05-27 11:13 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        cmd = f'gluster vol status {self.vol_name}'
I think we have a volume_status function in Redant. Please use that. The idea is to use the ops functions whenever they're available and not to recreate their functionality again and again in test cases.

2021-05-27 11:40 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +            raise Exception("Unexpected!!")
That is the case when the error message is other than "failed to find brick directory" which is unexpected.I will complete it

2021-05-27 11:42 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +            redant.logger.info("Volume hasn't started hence no status for it.")
first one for raising exception err_mssg is other than the expected one..second one is just for logging(I guess its not required).My bad.

2021-05-27 11:42 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        ret = redant.execute_command(cmd, self.server_list[0])
ACK

2021-05-27 11:43 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        redant.volume_stop(self.vol_name, self.server_list[0])
ack

2021-05-27 11:43 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +            raise Exception("Volume status erraneous")
Same here,will change

2021-05-27 11:43 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        redant.logger.info("Fetch all the bricks of the volume")
Ack

2021-05-27 11:44 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        cmd = f'gluster vol status {self.vol_name}'
Ack

2021-05-31 13:49 UTC, nik-redhat requested changes
Please add test run result after making the changes, and only then request for re-review.

2021-05-31 13:49 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        redant.volume_stop(self.vol_name, self.server_list[0])
Move this above the `Fetching brick list` comment.

2021-05-31 13:49 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        brick_list = redant.es.get_brickdata(self.vol_name)
Use the function `get_all_bricks`. Check the [brick_ops_doc](https://github.com/srijan-sivakumar/redant/blob/main/docs/BP/Ops/brick_ops.md) for refeerence.

2021-05-31 13:49 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        random_brick_path = random.choice(random_brick[1])
It should be split instead, please check the working after updating the above code to use get_all_bricks

2021-05-31 13:49 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if err_msg not in ret['msg']['opErrstr']:
Before this check, do a check for the `error_code` == 0

2021-05-31 13:49 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['msg']['opErrstr'] != f'Volume {self.vol_name} is not started':
Add a check before this check for `error_code`.

2021-05-31 13:49 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['msg']['opErrstr'] != f'Volume {self.vol_name} is not started':
Also, it might require `rstrip('\n')` have you confirmed the working of the TC?

2021-05-31 15:21 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['msg']['opErrstr'] != f'Volume {self.vol_name} is not started':
ACK

2021-05-31 15:22 UTC, neesingh-rh commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['msg']['opErrstr'] != f'Volume {self.vol_name} is not started':
Its not required.

2021-05-31 15:30 UTC, neesingh-rh commented
![image](https://user-images.githubusercontent.com/79842675/120215273-26905780-c253-11eb-920d-09ce83a81d54.png)

2021-05-31 17:14 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +            excep (bool): To bypass or not to bypass the exception handling.
not needed, it has been added above already.

2021-06-03 11:51 UTC, srijan-sivakumar commented
@aujjwal-redhat just test the case once so as to re-assure with latest changes.

2021-06-03 11:53 UTC, aujjwal-redhat commented
> @aujjwal-redhat just test the case once so as to re-assure with latest changes.

yeah running already. waiting for the results.

2021-06-03 11:54 UTC, aujjwal-redhat commented
```js
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_volume_status_with_absent_bricks
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 23.794852018356323 |
|     rep     |     PASS    | 23.931774377822876 |
|   dist-rep  |     PASS    | 29.602852821350098 |
|     disp    |     PASS    | 29.248443603515625 |
|  dist-disp  |     PASS    | 37.676634788513184 |
|     arb     |     PASS    | 24.161861419677734 |
+-------------+-------------+--------------------+



Framework runtime : 207.5736448764801
```

2021-06-03 11:56 UTC, srijan-sivakumar approved these changes

2021-06-03 11:57 UTC, merged

2021-06-03 12:00 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['error_code'] != 0 and err_msg not in ret['msg']['opErrstr']:
It would have been better to check the `ret['msg']['opRet']` value as well, `error_code` doesn't always give the correct value.

2021-06-03 12:00 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['error_code'] != 0 and ret['msg']['opErrstr'] !=\
Same as above

2021-06-03 12:01 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['error_code'] != 0 and err_msg not in ret['msg']['opErrstr']:
Ok I will submit a patch. : )
Thanks @nik-redhat for the review

2021-06-03 12:01 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_volume_status_with_absent_bricks.py
> +        if ret['error_code'] != 0 and ret['msg']['opErrstr'] !=\
Ack