[Test][Common][Doc] Brick remove enhancement
srijan-sivakumar/redant pull request #519
Opened 2021-05-30 13:02 UTC by srijan-sivakumar

1. Migrated the test case: `test_rebalance_spurious`
2. Added fattr based functions in io_ops
3. Modified remove_brick function in brick_ops
4. Made corresponding changes in docs
5. Removed a bad example test
6. Modified affected tests based on remove_brick
operation
    
Fixes: #514 

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

2021-05-30 13:03 UTC, srijan-sivakumar commented
Following are the test output of the tests which were changed

```
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py -ll D -sptest_remove_brick_when_quorum_not_met-dist PASS

Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_remove_brick_when_quorum_not_met
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|     dist    |     PASS    | 261.9339497089386 |
+-------------+-------------+-------------------+



Framework runtime : 265.9315333366394
```

```
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/glusterd/test_rebalance_spurious.py -ll D -sp
vol_create_test-dist PASS

test_rebalance_spurious-dist PASS

vol_destroy_test-dist PASS

Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   1   |    100.0     |
|   Disruptive  |   0   |      0       |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 vol_create_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 12.706926822662354 |
+-------------+-------------+--------------------+

 test_rebalance_spurious
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 27.317294597625732 |
+-------------+-------------+--------------------+

 vol_destroy_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 12.259228229522705 |
+-------------+-------------+--------------------+



Framework runtime : 55.193201780319214
```

2021-05-31 05:39 UTC, nik-redhat requested changes

2021-05-31 05:39 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +        ret = self.execute_abstract_op_node(cmd, node)
I think we are not using abstract ops in brick ops :thinking: , so this will not work.

2021-05-31 05:39 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +        if option in ['commit', 'force']:
I am not sure, but there is `commit force` as well?

2021-05-31 05:39 UTC, nik-redhat commented on tests/functional/glusterd/test_rebalance_spurious.py
> +            if not self.check_flag:
We also need to clear out the files create under brick dir.

2021-05-31 05:39 UTC, nik-redhat commented on tests/functional/glusterd/test_rebalance_spurious.py
> +# nonDisruptive;dist
Shouldn't this be a disruptive test, as we are trying to remove bricks in this case? And, altering data in brick dir?

2021-05-31 05:39 UTC, nik-redhat commented on tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py
>          # immediately in volume status after glusterd stop
We can modify it to use `wait_for_vol_process_to_be_online` and then update the logic based on that?
You can either update the todo to use that or do the code change yourself :sweat_smile: , thought that function has some updates and once one of my PR is merged you can do so, if you wish to change.

2021-05-31 06:01 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +        if option in ['commit', 'force']:
Not sure..haven't seen it any test cases...maybe we can handle it if need be.

2021-05-31 06:01 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_rebalance_spurious.py
> +            if not self.check_flag:
oh..that'll be done in parent terminate.

2021-05-31 06:02 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_rebalance_spurious.py
> +# nonDisruptive;dist
Naah..because this isn't affecting other test cases. Hence non disruptive.

2021-05-31 06:02 UTC, nik-redhat commented on tests/functional/glusterd/test_rebalance_spurious.py
> +            if not self.check_flag:
We do handle it currently, or that need to be updated?

2021-05-31 06:02 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py
>          # immediately in volume status after glusterd stop
We can modify this later..is what I think...it is working for now. Let's simplify it once we have some breathing space.

2021-05-31 06:07 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +        ret = self.execute_abstract_op_node(cmd, node)
Well....mixin is the person to note here. What we can do here is to prevent confusion, add the inheritance.

2021-05-31 06:16 UTC, nik-redhat approved these changes

2021-05-31 06:17 UTC, merged