Migrated test_enable_brickmux_create_and_stop_three_volumes
srijan-sivakumar/redant pull request #564
Opened 2021-06-01 13:43 UTC by aujjwal-redhat

Migrated the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py)

Updates: #292

Fixes: #560

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-01 13:44 UTC, aujjwal-redhat commented
@srijan-sivakumar @nik-redhat 
```js
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py -sp
Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-rep-0
Server: 10.70.43.74
Count: 1
Brick: 10.70.43.115:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-rep-1
Server: 10.70.43.115
Count: 1
Brick: 10.70.41.159:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-rep-2
Server: 10.70.41.159
Count: 1
test_enable_brickmux_create_and_stop_three_volumes-rep PASS

Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-rep-0
Server: 10.70.43.74
Count: 2
test_enable_brickmux_create_and_stop_three_volumes-dist-rep FAIL

Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-0
Server: 10.70.43.74
Count: 3
test_enable_brickmux_create_and_stop_three_volumes-dist FAIL

Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-disp-0
Server: 10.70.43.74
Count: 3
test_enable_brickmux_create_and_stop_three_volumes-disp FAIL

Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |     25.0     |
|     Total     |   1   |     25.0     |
+---------------+-------+--------------+
Table:
 test_enable_brickmux_create_and_stop_three_volumes
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|     rep     |     PASS    |  69.383873462677  |
|   dist-rep  |     FAIL    | 63.97100210189819 |
|     dist    |     FAIL    | 63.32441473007202 |
|     disp    |     FAIL    | 68.51646661758423 |
+-------------+-------------+-------------------+



Framework runtime : 268.1764931678772
```

This test case will fail because I have a 3 server setup.
This will pass for the failed volumes in a 6 server setup.

2021-06-01 13:46 UTC, aujjwal-redhat commented
I tried to check the bricks on each server for each vol type:
```js
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py -sp
Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-rep-0
Server: 10.70.43.74
Brick: 10.70.43.115:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-rep-1
Server: 10.70.43.115
Brick: 10.70.41.159:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-rep-2
Server: 10.70.41.159
test_enable_brickmux_create_and_stop_three_volumes-rep PASS

Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-rep-0
Server: 10.70.43.74
Brick: 10.70.43.115:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-rep-1
Server: 10.70.43.115
Brick: 10.70.41.159:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-rep-2
Server: 10.70.41.159
Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-rep-3
Server: 10.70.43.74
Brick: 10.70.43.115:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-rep-4
Server: 10.70.43.115
Brick: 10.70.41.159:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-rep-5
Server: 10.70.41.159
test_enable_brickmux_create_and_stop_three_volumes-dist-rep PASS

Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-0
Server: 10.70.43.74
Brick: 10.70.43.115:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-1
Server: 10.70.43.115
Brick: 10.70.41.159:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-2
Server: 10.70.41.159
Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-dist-3
Server: 10.70.43.74
test_enable_brickmux_create_and_stop_three_volumes-dist PASS

Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-disp-0
Server: 10.70.43.74
Brick: 10.70.43.115:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-disp-1
Server: 10.70.43.115
Brick: 10.70.41.159:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-disp-2
Server: 10.70.41.159
Brick: 10.70.43.74:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-disp-3
Server: 10.70.43.74
Brick: 10.70.43.115:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-disp-4
Server: 10.70.43.115
Brick: 10.70.41.159:/glusterfs/brick/test_enable_brickmux_create_and_stop_three_volumes-disp-5
Server: 10.70.41.159
test_enable_brickmux_create_and_stop_three_volumes-disp PASS

Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_enable_brickmux_create_and_stop_three_volumes
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|     rep     |     PASS    | 69.02504348754883 |
|   dist-rep  |     PASS    |  75.0153136253357 |
|     dist    |     PASS    | 89.50001668930054 |
+-------------+-------------+-------------------+
```

2021-06-02 05:32 UTC, aujjwal-redhat commented
@srijan-sivakumar @nik-redhat do lemme know for the changes. : )

2021-06-02 06:57 UTC, nik-redhat requested changes

2021-06-02 06:57 UTC, nik-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +            print(f"Brick: {brick}\nServer: {server}")
nit: Remove this

2021-06-02 06:57 UTC, nik-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +            print(f"Count: {count}")
Same as above

2021-06-02 06:57 UTC, nik-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +        super().terminate()
Can be removed, it will be handled in the parent terminate

2021-06-02 07:00 UTC, nik-redhat commented
But even if we enable brick multiplex bricks of different volumes won't be linked together, so we will not get the count as 1 :thinking:

2021-06-02 07:36 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +            print(f"Brick: {brick}\nServer: {server}")
Yeah. Just kept for the above output : )
Will remove it

2021-06-02 07:36 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +            print(f"Count: {count}")
Ack

2021-06-02 07:37 UTC, aujjwal-redhat commented
> But even if we enable brick multiplex bricks of different volumes won't be linked together, so we will not get the count as 1

: | Sorry, didn't get it exactly.

2021-06-02 07:38 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +        super().terminate()
Ack

2021-06-02 08:06 UTC, srijan-sivakumar commented
> But even if we enable brick multiplex bricks of different volumes won't be linked together, so we will not get the count as 1 thinking

@nik-redhat actually bricks of different volumes will be linked together if their configurations are similar. That's actually a cool point of the brick-mux feature.

2021-06-02 09:24 UTC, nik-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +        brick_list = self.redant.get_all_bricks(self.vol_name,
Check for Null after this

2021-06-02 09:27 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
> +        brick_list = self.redant.get_all_bricks(self.vol_name,
Ack

2021-06-02 09:48 UTC, srijan-sivakumar approved these changes
LGTM

2021-06-02 09:53 UTC, nik-redhat approved these changes

2021-06-02 09:54 UTC, merged