Migrated TC test_glusterd_replace_brick
srijan-sivakumar/redant pull request #568
Opened 2021-06-01 16:02 UTC by nik-redhat

Migrated TC [test_glusterd_remove_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_replace_brick.py)

Fixes: #559 
Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

2021-06-01 19:35 UTC, nik-redhat commented
```
Table:
 test_glusterd_replace_brick
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|     rep     |     PASS    | 34.62212252616882 |
|   dist-rep  |     PASS    | 39.46930265426636 |
|     disp    |     PASS    | 32.27100896835327 |
|  dist-disp  |     PASS    |  37.178462266922  |
+-------------+-------------+-------------------+

Framework runtime : 144.5557861328125
```

test_add_brick_when_quorum_not_met:
```
Table:
 test_add_brick_when_quorum_not_met
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|     dist    |     PASS    | 244.1784462928772 |
+-------------+-------------+-------------------+

Framework runtime : 246.00085139274597
```

```
Table:
 test_brick_ops
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   dist-rep  |     PASS    | 57.160343408584595 |
|     dist    |     PASS    | 46.90464186668396  |
|     rep     |     PASS    | 51.218979358673096 |
+-------------+-------------+--------------------+

Framework runtime : 156.10882544517517
```

```
Table:
 test_create_vol_with_used_bricks
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|   Generic   |     PASS    | 59.77846097946167 |
+-------------+-------------+-------------------+

Framework runtime : 63.947874784469604
```

```
Table:
 test_peer_status
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   Generic   |     PASS    | 27.104591131210327 |
+-------------+-------------+--------------------+

Framework runtime : 28.890183448791504
```

```
Table:
 test_rebalance_new_node
 
+-------------+-------------+------------------+
| Volume Type | Test Result | Time taken (sec) |
+-------------+-------------+------------------+
|   Generic   |     PASS    | 71.916184425354  |
+-------------+-------------+------------------+

Framework runtime : 77.24169707298279
```

2021-06-01 19:36 UTC, nik-redhat commented
There is some problem with the test_probe_hostname case or in the peer ops which this case is using.

2021-06-01 19:37 UTC, nik-redhat commented
@srijan-sivakumar do mark this TC as excluded in the CI, else other TCs will be affected.
Other than that, we are good with this PR.

2021-06-02 06:52 UTC, srijan-sivakumar requested changes

2021-06-02 06:52 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +        # if not src_brick:
will these comments be kept for future..or was it some experiment

2021-06-02 06:52 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +        if delete_brick:
instead of deletion, we can just push the old brick to cleands. Where the cleanup will be taken care..

2021-06-02 06:52 UTC, srijan-sivakumar commented on common/ops/gluster_ops/volume_ops.py
> +    #     Get the subvolumes in the given volume
A TODO or comment might help in understanding why this is kept commented for now.

2021-06-02 06:53 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +        # if not src_brick:
Kept for future, once we have function for `get_subvols`

2021-06-02 06:55 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +    #     Get the subvolumes in the given volume
Ack

2021-06-02 07:53 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +        # if not src_brick:
cool.

2021-06-02 08:01 UTC, srijan-sivakumar approved these changes
LGTM

2021-06-02 08:16 UTC, merged