Migration of test_volume_create.py
srijan-sivakumar/redant pull request #583
Opened 2021-06-02 09:09 UTC by nishith-vihar

Migration of [test_volume_create.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_create.py) from glusto to redant

Updates: #292
Fixes: #562 
Signed-off-by: Nishith Vihar Sakinala nsakinal@redhat.com

2021-06-02 09:09 UTC, nishith-vihar commented
Required 4 servers in the test case logic

2021-06-07 05:51 UTC, nik-redhat commented
Rebase the PR, and add a check at the top for the servers and let's take this PR to completion.

2021-06-07 06:36 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
>      def volume_create(self, volname: str, node: str, conf_hash: dict,
A new function for this is added, `volume_create_with_custome_brick` or something of that sort, use that.

2021-06-07 06:39 UTC, nishith-vihar commented on common/ops/gluster_ops/volume_ops.py
>      def volume_create(self, volname: str, node: str, conf_hash: dict,
Ack

2021-06-07 06:59 UTC, nik-redhat requested changes

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +        ret = redant.volume_start(self.volume_name1, self.server_list[0],
ret not needed

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +            raise Exception("Unexpected: Successfully created the volume "
You are raising an exception here and handling it the next line by saying `expected` which is not true.
Instead, use the excep flag and check the error_code in the return value and raise an exception accordingly.

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +            raise Exception("Unexpected: Successfully created the volume with "
Same as above

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +
Use the setup_test function to override the volume creation in the parent_run_test.

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +
Also, we can simply make it `disruptive`, we don't need to create a dist volume in the parent_run_test

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +                                self.brick_roots, True)
No need for `force`, also, pass `False` to except to get the return value accordingly.

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +                               "non existing brick path")
Same as above

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +                               "bricks which are part of another cluster")
Same as above.
No need for `force` and use except flag for return value

2021-06-07 06:59 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +                               "brick whose node is down")
Same as above

2021-06-07 09:16 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +        ret = redant.volume_start(self.volume_name1, self.server_list[0],
Ack

2021-06-07 09:16 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +            raise Exception("Unexpected: Successfully created the volume "
Ack

2021-06-07 09:17 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +            raise Exception("Unexpected: Successfully created the volume with "
Ack

2021-06-07 09:22 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +                               "brick whose node is down")
Ack

2021-06-07 09:25 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +                               "non existing brick path")
Ack

2021-06-07 09:27 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +                                self.brick_roots, True)
I don't think we need to set excep flag to False as we are not using the ret value anywhere

2021-06-07 09:28 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +                               "bricks which are part of another cluster")
I dont think we would need to set the excep flag to False here also. same as above

2021-06-07 09:30 UTC, nishith-vihar commented on tests/functional/glusterd/test_volume_create.py
> +
I think it would be just enough to remove the dist volume just make it disruptive

2021-06-07 09:39 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +
Yes, that would do as well.

2021-06-07 10:05 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +                                self.brick_roots, True)
The only reason to use `False` is that if we except the Exception here and just log it then we will have to logs now at the ERROR level done by the abstract ops and another here at INFO level saying it is expected which will create disparities.

2021-06-07 10:07 UTC, nik-redhat commented on tests/functional/glusterd/test_volume_create.py
> +            excep = False
Hey this is not the correct way of using it, we need to pass it in the function itself, check the function definition for the usage.

2021-06-07 11:38 UTC, nik-redhat approved these changes

2021-06-07 11:39 UTC, nik-redhat approved these changes

2021-06-07 11:47 UTC, merged