Migrating test_reserve_limt_change_wile_rebalance.py
srijan-sivakumar/redant pull request #597
Opened 2021-06-02 15:12 UTC by nishith-vihar

Migrating [test_reserve_limt_change_while_rebalance.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py) from glusto to redant.             
                                                                               
Updates: #292:                                                                  
Fixes: 585                                                                                                            
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-06-02 15:25 UTC, aujjwal-redhat submitted a review, later dismissed

2021-06-02 15:25 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +         value say (70)
nit: Indent : )

2021-06-02 15:25 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +        1) Create a distributed-replicated volume and start it.
Since its not part of the run test Ig we can remove it. Just a suggestion.

2021-06-02 15:25 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +
terminate is needed.
wait for rebalance to complete function
```js
if not wait_for_rebalance_to_complete( self.vol_name,
                                                     self.server_list[0]):
```

2021-06-02 15:27 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +         value say (70)
Ack

2021-06-02 15:27 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +        1) Create a distributed-replicated volume and start it.
Actually let it be it will be clear to the user

2021-06-02 15:28 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +
Ack

2021-06-02 15:38 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +        1) Create a distributed-replicated volume and start it.
Yeah that's fine too : )

2021-06-02 16:07 UTC, nik-redhat commented
Test run? :)

2021-06-02 16:08 UTC, nik-redhat commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +        redant.run_linux_untar(self.clients[0], self.mountpoint,
self.client_list[0]

2021-06-02 16:09 UTC, nik-redhat commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +                self.vol_name, self.server_list[0])
It's good to keep the right part of the assignment operator on the right only :sweat_smile: , indent it accordingly

2021-06-02 18:08 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +                self.vol_name, self.server_list[0])
Keeping it to the right is against the flake rules. That is why I had to keep it this way.

2021-06-02 18:08 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +        redant.run_linux_untar(self.clients[0], self.mountpoint,
Ack

2021-06-02 18:16 UTC, nik-redhat commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +                self.vol_name, self.server_list[0])
Encapsulate it within a bracket, it should work.

2021-06-03 05:50 UTC, srijan-sivakumar requested changes

2021-06-03 05:50 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +        mul_factor = 1
```
mul_factor = 3
            _, br_cmd = redant.form_brick_cmd(self.server_list,
                                              self.brick_roots,
                                              self.vol_name, mul_factor, True)
            redant.add_brick(self.vol_name, br_cmd, self.server_list[0],
                             replica_count=3)
```

Add brick to dist-rep has to be consistent with the subvolumes...above code example is for making a 2x3 into 3x3...we can also convert the 2x3 into 2x4, but 3x3 would be a better idea as it's standard.

2021-06-03 05:50 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +# nonDisruptive;dist-rep
make it disruptive as we still don't have the feature to convert the volume back to old state with respect to brick counts.

2021-06-03 05:51 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +        mul_factor = 1
Ack

2021-06-03 05:51 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +# nonDisruptive;dist-rep
Ack

2021-06-03 06:01 UTC, srijan-sivakumar commented
```
(v1) [root@f05-h06-000-1029p redant]# python3 core/redant_main.py -c ../config.yml -t tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py -ll D -sp
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_reserve_limt_change_while_rebalance-dist-rep
✔ test_reserve_limt_change_while_rebalance-dist-rep Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_reserve_limt_change_while_rebalance
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|   dist-rep  |     PASS    | 56.78188443183899 |
+-------------+-------------+-------------------+



Framework runtime : 61.966452836990356

✔ Tearing down successful.
```

2021-06-03 06:02 UTC, srijan-sivakumar requested changes

2021-06-03 06:02 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +    def run_test(self, redant):
Just a final remark...add a conditional here for minimum server requirement.

2021-06-03 06:03 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +    def run_test(self, redant):
There is no minimum server requirement right

2021-06-03 06:03 UTC, nishith-vihar commented on tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
> +    def run_test(self, redant):
It runs with just 3 servers

2021-06-03 06:16 UTC, srijan-sivakumar approved these changes

2021-06-03 06:17 UTC, merged