Migrating test_add_identical_brick_new_node.py
srijan-sivakumar/redant pull request #604
Opened 2021-06-03 08:32 UTC by nishith-vihar

Migrating [test_add_identical_brick_new_node.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_add_identical_brick_new_node.py) from glusot to redant
    
Updates: #292
Fixes: #598
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-06-03 09:28 UTC, aujjwal-redhat requested changes

2021-06-03 09:28 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        bricks_list = redant.es.get_all_bricks_list(self.volume_name1)
you can instrad call the get_all_bricks() from brick ops instead of environ. That gives the bricks list from the volume info. Even in glusto they have used the get all bricks from brick libs.

2021-06-03 09:28 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        ret = redant.peer_probe(self.server_list[1], self.server_list[0])
we can remove this ret : )

2021-06-03 09:28 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        time.sleep(2)
Instead of this we can have a check is_peer_connected to prevent spurious failures.

2021-06-03 09:28 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        ret = redant.add_brick(self.volume_name1, brick_str,
remove ret : )

2021-06-03 17:32 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        bricks_list = redant.es.get_all_bricks_list(self.volume_name1)
Ack

2021-06-03 17:32 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        ret = redant.peer_probe(self.server_list[1], self.server_list[0])
Ack

2021-06-03 17:33 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        time.sleep(2)
I have replaced peer_probe with peer_probe_servers with validate option.

2021-06-03 17:33 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        ret = redant.add_brick(self.volume_name1, brick_str,
Ack

2021-06-03 18:01 UTC, nishith-vihar commented
```
✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_add_identical_brick_new_node-Generic
✔ test_add_identical_brick_new_node-Generic Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_add_identical_brick_new_node
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|   Generic   |     PASS    | 42.26495814323425 |
+-------------+-------------+-------------------+



Framework runtime : 53.134398460388184

✔ Tearing down successful.
```

2021-06-03 18:22 UTC, nik-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +                                             self.volume_name1, 1)
Are you sure this gives an identical brick?

2021-06-03 18:23 UTC, nik-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +            raise Exception(f"Failed to fetch bricks for {self.volume_name1}")
Also, check for `None` here instead of 0, we won't be getting 0 generally until something scary has happened but `None` might come if the command failed.

2021-06-03 18:24 UTC, nik-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        redant.peer_probe_servers(self.server_list[1], self.server_list[0],
Check the return value and raise exception accordingly

2021-06-03 18:25 UTC, nik-redhat commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        redant.logger.info("Get all the bricks of the volume")
This logging is not needed

2021-06-04 04:16 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +                                             self.volume_name1, 1)
Yes. According to the logic in form_brick_cmd brick_path is built using volname and {iteration+iter_add}. volname will be same for both and {iteration+iter_add} will be same if different node is given while forming the brick
```brick_path_val = (
                f"{brick_root[server_list[server_iter]]}/{volname}-"
                f"{iteration+iter_add}")```

2021-06-04 04:17 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +            raise Exception(f"Failed to fetch bricks for {self.volume_name1}")
Ack

2021-06-04 04:18 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        redant.peer_probe_servers(self.server_list[1], self.server_list[0],
Ack

2021-06-04 04:21 UTC, nishith-vihar commented on tests/functional/glusterd/test_add_identical_brick_new_node.py
> +        redant.logger.info("Get all the bricks of the volume")
Ack

2021-06-04 04:33 UTC, nishith-vihar commented
```
✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_add_identical_brick_new_node-Generic
✔ test_add_identical_brick_new_node-Generic Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_add_identical_brick_new_node
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   Generic   |     PASS    | 39.897451400756836 |
+-------------+-------------+--------------------+



Framework runtime : 51.07966470718384

✔ Tearing down successful.
```

2021-06-04 05:49 UTC, nik-redhat approved these changes

2021-06-04 05:55 UTC, aujjwal-redhat approved these changes
LGTM

2021-06-04 05:56 UTC, merged