Migrated test_probe_glusterd_down
srijan-sivakumar/redant pull request #627
Opened 2021-06-04 07:43 UTC by aujjwal-redhat

Migrated the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_probe_glusterd_down.py)

Updates: #292

Fixes: #582

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-04 07:45 UTC, aujjwal-redhat commented
@srijan-sivakumar @nik-redhat 
in the glusto TC they are adding a sleep of 150
```js
        # Bring down the network for sometime
        network_status = bring_down_network_interface(self.servers[1], 150)
```

While it was working perfectly even with sleep(10)
```js
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_probe_glusterd_down
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   Generic   |     PASS    | 27.136693716049194 |
+-------------+-------------+--------------------+



Framework runtime : 39.22702383995056
```

I still have given a 30 timeout in the patch.

2021-06-04 09:03 UTC, srijan-sivakumar commented on common/ops/support_ops/machine_ops.py
> +        interface = "eth0" if self.is_rhel7(node) else "enp1s0"
The network interfaces are not hardcoded to be eth0 or enp1o, for instance in my VM, it is eno1.

2021-06-04 12:30 UTC, aujjwal-redhat commented on common/ops/support_ops/machine_ops.py
> +        interface = "eth0" if self.is_rhel7(node) else "enp1s0"
Yeah true.

2021-06-04 12:49 UTC, aujjwal-redhat commented
```js
✔ test_probe_glusterd_down-Generic Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_probe_glusterd_down
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   Generic   |     PASS    | 40.419057846069336 |
+-------------+-------------+--------------------+



Framework runtime : 48.8894567489624

```

## Logs:

```js
[2021-06-04 18:15:01,571] INFO  - Running /sbin/ip a | grep BROADCAST on 10.70.43.115
[2021-06-04 18:15:01,651] DEBUG  - {'msg': ['2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000\n'], 'Flag': True, 'node': '10.70.xx.xxx', 'cmd': '/sbin/ip a | grep BROADCAST', 'error_code': 0}
[2021-06-04 18:15:01,651] INFO  - Running echo  "ip link set enp1s0 down
sleep 30
ip link set enp1s0 up"> 'test.sh' on 10.70.43.115
[2021-06-04 18:15:01,729] DEBUG  - {'msg': [], 'Flag': True, 'node': '10.70.43.115', 'cmd': 'echo  "ip link set enp1s0 down\nsleep 30\nip link set enp1s0 up"> \'test.sh\'', 'error_code': 0}

```

2021-06-04 15:45 UTC, srijan-sivakumar requested changes

2021-06-04 15:45 UTC, srijan-sivakumar commented on common/ops/support_ops/machine_ops.py
> +        int_cmd = "/sbin/ip a | grep BROADCAST"
ok...second level of question, what if we have multiple network interfaces ? It might be possible that out of say 4 network interfaces, only one is configured for glusterfs. So even if we down the other 3, it wouldn't affect glusterfs. Probabaly you'd need to take a reverse approach here. Find out from cmdline as to what interface is being used by gluster process and then down that interface.

2021-06-05 05:23 UTC, nik-redhat commented on tests/functional/glusterd/test_probe_glusterd_down.py
> +                                    f"{ret['error_msg']}")
Not needed, it is already done in the parent terminate

2021-06-06 09:45 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_probe_glusterd_down.py
> +                                    f"{ret['error_msg']}")
Ack

2021-06-06 09:45 UTC, aujjwal-redhat commented on common/ops/support_ops/machine_ops.py
> +        int_cmd = "/sbin/ip a | grep BROADCAST"
How exactly do we do that : | ?

2021-06-07 08:47 UTC, aujjwal-redhat commented
```js
[2021-06-07 14:10:56,899] INFO  - Running ps -aux | grep glusterd on 10.70.43.115
[2021-06-07 14:10:56,996] DEBUG  - {'msg': ['root       63924  1.0  0.5 231556 11188 ?        Ssl  14:10   0:00 /usr/local/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO\n', 'root       63968  0.0  0.1   6692  3352 ?        Ss   14:10   0:00 bash -c ps -aux | grep glusterd\n', 'root       63979  0.0  0.0   6184   720 ?        S    14:10   0:00 grep glusterd\n'], 'Flag': True, 'node': '10.70.43.115', 'cmd': 'ps -aux | grep glusterd', 'error_code': 0}
[2021-06-07 14:10:56,997] INFO  - Running cat /proc/63924/net/route on 10.70.43.115
[2021-06-07 14:10:57,074] DEBUG  - {'msg': ['Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\t\tMTU\tWindow\tIRTT                                                       \n', 'enp1s0\t00000000\tFE2B460A\t0003\t0\t0\t100\t00000000\t0\t0\t0                                                                           \n', 'enp1s0\t0028460A\t00000000\t0001\t0\t0\t100\t00FCFFFF\t0\t0\t0                                                                           \n'], 'Flag': True, 'node': '10.70.43.115', 'cmd': 'cat /proc/63924/net/route', 'error_code': 0}
[2021-06-07 14:10:57,075] INFO  - Running echo  "ip link set enp1s0 down
sleep 30
ip link set enp1s0 up"> 'test.sh' on 10.70.43.115

```

2021-06-07 11:04 UTC, srijan-sivakumar commented
@aujjwal-redhat can you attach the results ?

2021-06-07 11:07 UTC, aujjwal-redhat commented
```js
Table:
 test_probe_glusterd_down
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|   Generic   |     PASS    | 53.22862792015076 |
+-------------+-------------+-------------------+



Framework runtime : 63.61381435394287

```
@srijan-sivakumar  added the result

2021-06-07 11:14 UTC, srijan-sivakumar approved these changes
LGTM

2021-06-07 11:14 UTC, merged