Migration of test_detach_node_used_to_mount.py
srijan-sivakumar/redant pull request #633
Opened 2021-06-07 05:44 UTC by nishith-vihar

Migration of [test_detach_node_used_to_mount.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_detach_node_used_to_mount.py) from glusto to redant.
get_fattr_list function is added in the io_ops which is needed in the test case.

Updates: #292
Fixes: #626
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-06-07 05:47 UTC, nishith-vihar commented
Requires 3 servers and 1 client for the test case run.

2021-06-07 05:48 UTC, nik-redhat commented
You can fix the lint, then I will check in my env and update the results.

2021-06-07 06:19 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +            host (str): The hostname/ip of the remote system.
nit: node

2021-06-07 06:19 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +            fqpath (str): The fully-qualified path to the file.
interchange the sequence of the args, i.e, first fqpath then node

2021-06-07 06:21 UTC, nik-redhat commented
The test requires 4 servers at least and 1 client which is not among that 4 servers.
Also, @nishith-vihar in this case you will have to mount the volume yourself and not use the predefined mount code, you can use the `setup_test` function for this. We need to mount the volume using the 4th server, and then detach that 4th server and do the operations. Check the glusto again for the logic.

2021-06-07 06:28 UTC, nik-redhat requested changes

2021-06-07 06:28 UTC, nik-redhat commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +                                                  self.server_list[0]))
As per the TC, we don't have to wait for it to complete, rather simply stop it and continue.

2021-06-07 06:28 UTC, nik-redhat commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +        brick_str = redant.form_brick_cmd(self.server_list, self.brick_roots,
the form_brick_cmd function returns `dict, string` so update the return value accordingly.

2021-06-07 06:28 UTC, nik-redhat commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +        redant.logger.info("Starting rebalance on the volume")
logging not required

2021-06-07 06:28 UTC, nik-redhat commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +        brick_list = redant.get_all_bricks(self.vol_name, self.server_list[0])
We only need to check on the newly added bricks, don't fetch the complete brick list. Convert the brick_string received from the `form_brick_cmd` to a list nd use that.

2021-06-07 06:44 UTC, nishith-vihar commented on common/ops/support_ops/io_ops.py
> +            host (str): The hostname/ip of the remote system.
Ack

2021-06-07 06:44 UTC, nishith-vihar commented on common/ops/support_ops/io_ops.py
> +            fqpath (str): The fully-qualified path to the file.
Ack

2021-06-07 06:49 UTC, nishith-vihar commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +                                                  self.server_list[0]))
This is in the terminate function right. Dont we need to wait for rebalance to complete if the test fails midway?

2021-06-07 06:51 UTC, nishith-vihar commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +        brick_str = redant.form_brick_cmd(self.server_list, self.brick_roots,
Ack

2021-06-07 06:52 UTC, nishith-vihar commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +        redant.logger.info("Starting rebalance on the volume")
Ack

2021-06-07 07:00 UTC, nik-redhat commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +                                                  self.server_list[0]))
Nope we don't want to wait for it, we can simply stop it and proceed.

2021-06-07 07:17 UTC, nishith-vihar commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +                                                  self.server_list[0]))
Ack

2021-06-07 07:39 UTC, nishith-vihar commented on tests/functional/glusterd/test_detach_node_used_to_mount.py
> +        brick_list = redant.get_all_bricks(self.vol_name, self.server_list[0])
Ack

2021-06-07 10:05 UTC, nik-redhat commented
If it's ready for review, then do mark it accordingly @nishith-vihar :)

2021-06-07 14:47 UTC, nik-redhat reviewed
lgtm.

2021-06-07 14:48 UTC, nik-redhat commented
@srijan-sivakumar could you please test it in the CI?

2021-07-02 13:41 UTC, aujjwal-redhat approved these changes
LGTM

2021-07-02 13:51 UTC, aujjwal-redhat approved these changes

2021-07-02 14:00 UTC, srijan-sivakumar commented
@nik-redhat let me know if everything's fine. Blocked on your change request. I think those changes are taken care of. But still better to check it once.

2021-07-02 14:06 UTC, nik-redhat approved these changes
LGTM.

2021-07-02 14:08 UTC, merged