Migrated test_remove_brick_scenarios
srijan-sivakumar/redant pull request #668
Opened 2021-06-16 07:07 UTC by aujjwal-redhat

Migrated the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_remove_brick_scenarios.py)

Fixes: #667

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-16 10:54 UTC, aujjwal-redhat commented
```js
✔ Environment setup successful.
✔ Running test case : test_remove_brick_scenarios-dist-rep
✔ test_remove_brick_scenarios-dist-rep Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_remove_brick_scenarios
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   dist-rep  |     PASS    | 2602.0067014694214 |
+-------------+-------------+--------------------+



Framework runtime : 2613.1035239696503

```

2021-06-17 16:10 UTC, srijan-sivakumar requested changes

2021-06-17 16:10 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_remove_brick_scenarios.py
> +        remove_brick_list_non_existent = [bricks_list[0] + 'non-existent',
use f strings for string concatenation.

2021-06-17 16:13 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_remove_brick_scenarios.py
> +        remove_brick_list_non_existent = [bricks_list[0] + 'non-existent',
Ack

2021-06-17 17:40 UTC, aujjwal-redhat commented
```js
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_remove_brick_scenarios
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   dist-rep  |     PASS    | 2491.1046924591064 |
+-------------+-------------+--------------------+



Framework runtime : 2501.6858842372894
```

2021-06-18 05:40 UTC, srijan-sivakumar commented
2k seconds!!

2021-06-18 05:53 UTC, aujjwal-redhat commented
> 2k seconds!!

yeah, the IO operation is quite heavy. It creates 100000 files and I guess gluster takes time in such large number of files.
For less number of files it took less time. Checked with 10, 100, 1000 and 10000 as well.

2021-06-21 07:37 UTC, nik-redhat commented
If we use a lesser number of files will that be a problem? If not let's reduce the number to 10000 and see if that works.

2021-06-21 07:45 UTC, aujjwal-redhat commented
> If we use a lesser number of files will that be a problem? If not let's reduce the number to 10000 and see if that works.

yeah 10000 works as well and it takes less time. But will that be fine for the test case logic coz 100000 files are also working. Just the time is too much. :-|

2021-06-24 11:12 UTC, srijan-sivakumar commented
> > If we use a lesser number of files will that be a problem? If not let's reduce the number to 10000 and see if that works.
> 
> yeah 10000 works as well and it takes less time. But will that be fine for the test case logic coz 100000 files are also working. Just the time is too much. :-|

Technically the idea of creating large number of files is to have file entries under all bricks and not just some bricks. This is because of how gluster works.
1. With the help of hash determined from the file, it is decided which subvolume that file will reside, though in case of the dirs, they are placed on all subvolumes.
2. Coming to layout, which we can simply understand as the range of hashes attached to each brick and files whose hash falls under that range will be stored in those said bricks. Add and remove brick in this way would re-trigger how the layout is assigned to all bricks, hence the need to re-trigger fix-layout which will redo the calculations and assign new layouts, but that'd mean some files will exist in bricks where they're now not supposed to. Now what I'm still unsure of is whether there is a separate migrate phase or would the fix-layout itself take care of the migrating of files. @nik-redhat any idea ?

2021-06-25 07:57 UTC, nik-redhat commented
So, we have two ways to trigger rebalance for a volume:
1. `gluster v rebal VOLNAME fix-layout start`: This will only update the layout of the volumes in the process and won't migrate the data.
2. `gluster v rebal VOLNAME start`: This uses the `fix-layout and migration` strategy and does the above task as well as migrates the data based on the storage of the bricks, uniformly.

So, generally what we do is the second option, and the same is being done in our OPs. I think we can go ahead with the TC and run it for 100000 files. What say?

2021-06-25 13:14 UTC, srijan-sivakumar commented
> So, we have two ways to trigger rebalance for a volume:
> 
>     1. `gluster v rebal VOLNAME fix-layout start`: This will only update the layout of the volumes in the process and won't migrate the data.
> 
>     2. `gluster v rebal VOLNAME start`: This uses the `fix-layout and migration` strategy and does the above task as well as migrates the data based on the storage of the bricks, uniformly.
> 
> 
> So, generally what we do is the second option, and the same is being done in our OPs. I think we can go ahead with the TC and run it for 100000 files. What say?

As discussed offline ( off-github ), going ahead with this TC.

2021-06-25 16:28 UTC, srijan-sivakumar approved these changes

2021-06-25 16:28 UTC, merged