Added more volume ops
srijan-sivakumar/redant pull request #677
Opened 2021-06-18 05:43 UTC by aujjwal-redhat

Added log_volume_info_nad_status and is_volume_exported.

Fixes: #675

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-18 07:35 UTC, nik-redhat requested changes

2021-06-18 07:35 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +        if not excep and int(ret['msg']['opRet']) != 0:
opRet will have a string value, make it '0'

2021-06-18 07:35 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +        if not excep and int(ret['msg']['opRet']) != 0:
Actually, we don't need this an `excep` flag for this function. Just an empty dict check in the caller function shall do, if it doesn't work then something wrong with the command.

2021-06-18 07:35 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +            else:
Same as above

2021-06-18 07:35 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +                return True
Remove this part and simply keep a `return True` at the end.

2021-06-18 07:37 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
> +        if not excep and int(ret['msg']['opRet']) != 0:
Ack

2021-06-18 07:37 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
> +            else:
Ack

2021-06-18 07:37 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
> +                return True
Ack

2021-06-18 07:47 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
> +        if not excep and int(ret['msg']['opRet']) != 0:
But what if the command itself failed to execute. In that case there will be no dict.

2021-06-18 07:54 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +        if not excep and int(ret['msg']['opRet']) != 0:
Ah....true. Then, let's keep this check, just update it to compare string.

2021-06-18 07:54 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
> +        if not excep and int(ret['msg']['opRet']) != 0:
yeah

2021-06-18 08:19 UTC, nik-redhat commented
Can you update the code for the `get_vol_status` as well, to not do any logging and return in case of `excep=False` in the same PR?

2021-06-18 08:25 UTC, nik-redhat commented
And, with that a couple oof TC needs fixes like `test_gluster_detect_drop_of_outbound_traffic` and `test_volume_status_with_absent_bricks` do fix them as well.

2021-06-18 08:38 UTC, aujjwal-redhat commented
> Can you update the code for the `get_vol_status` as well, to not do any logging and return in case of `excep=False` in the same PR?

Ok

2021-06-18 08:57 UTC, aujjwal-redhat commented
```js
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_volume_status_with_absent_bricks
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 24.71252703666687  |
|     rep     |     PASS    | 32.111796855926514 |
|   dist-rep  |     PASS    | 34.945164918899536 |
|     disp    |     PASS    | 31.519803524017334 |
|  dist-disp  |     PASS    | 36.63633751869202  |
|     arb     |     PASS    | 32.81458806991577  |
|   dist-arb  |     PASS    | 36.21625828742981  |
+-------------+-------------+--------------------+
```

2021-06-18 09:05 UTC, nik-redhat commented on tests/functional/glusterd/test_gluster_detect_drop_of_outbound_traffic.py
>              raise Exception("Failed to get the vol status")
As per the above comment, it should fail, isn't it?

2021-06-18 09:23 UTC, aujjwal-redhat commented on tests/functional/glusterd/test_gluster_detect_drop_of_outbound_traffic.py
>              raise Exception("Failed to get the vol status")
yeah True. Ig the logic needs to be changed here. on it

2021-06-21 05:48 UTC, nik-redhat approved these changes

2021-06-21 05:48 UTC, merged