Added more functions in brick ops
srijan-sivakumar/redant pull request #681
Opened 2021-06-18 07:49 UTC by aujjwal-redhat

Added two functions in brick ops:
* delete_bricks
* is_broken_symlinks_present_on_bricks

Fixes: #678

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-18 08:29 UTC, nik-redhat requested changes

2021-06-18 08:29 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +                                             volname: str):
Mention the return type

2021-06-18 08:29 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +        Returns: Bool
Break to next line

2021-06-18 08:29 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +    def delete_bricks(self, bricks_list: list):
mention the return type

2021-06-18 08:37 UTC, aujjwal-redhat commented on common/ops/gluster_ops/brick_ops.py
> +                                             volname: str):
Ack

2021-06-18 08:37 UTC, aujjwal-redhat commented on common/ops/gluster_ops/brick_ops.py
> +        Returns: Bool
Ack

2021-06-18 08:37 UTC, aujjwal-redhat commented on common/ops/gluster_ops/brick_ops.py
> +    def delete_bricks(self, bricks_list: list):
Ack

2021-06-21 08:11 UTC, nik-redhat approved these changes

2021-06-21 08:17 UTC, merged