Added auth ops
srijan-sivakumar/redant pull request #683
Opened 2021-06-21 06:19 UTC by aujjwal-redhat

Added auth ops

Fixes: #682

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-21 14:23 UTC, aujjwal-redhat commented
> @aujjwal-redhat a small example might help. Maybe add this example inside test_vol_ops.py inside the example...

Ok

2021-06-21 15:05 UTC, aujjwal-redhat commented
@srijan-sivakumar @nik-redhat 
```js
Table:
 vol_create_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     rep     |     PASS    | 10.890544891357422 |
|     dist    |     PASS    | 11.318605422973633 |
|     disp    |     PASS    | 12.465857028961182 |
|     arb     |     PASS    | 17.174437284469604 |
|   dist-rep  |     PASS    | 21.366750478744507 |
|   dist-arb  |     PASS    | 16.636252403259277 |
|  dist-disp  |     PASS    | 13.74812388420105  |
+-------------+-------------+--------------------+

 test_vol_ops
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     rep     |     PASS    | 20.02519726753235  |
|     dist    |     PASS    |  20.7152898311615  |
|     arb     |     PASS    | 18.976844787597656 |
|     disp    |     PASS    | 20.29721736907959  |
|   dist-rep  |     PASS    | 25.11155652999878  |
|   dist-arb  |     PASS    | 27.036733865737915 |
|  dist-disp  |     PASS    | 20.204575300216675 |
+-------------+-------------+--------------------+

 vol_destroy_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     rep     |     PASS    | 12.48116946220398  |
|     dist    |     PASS    | 16.09177589416504  |
|     arb     |     PASS    | 12.84449815750122  |
|     disp    |     PASS    | 16.304376125335693 |
|   dist-rep  |     PASS    | 20.27171778678894  |
|   dist-arb  |     PASS    | 23.20875883102417  |
|  dist-disp  |     PASS    | 12.127867221832275 |
+-------------+-------------+--------------------+



Framework runtime : 216.72838377952576
```

2021-06-22 06:14 UTC, nik-redhat requested changes

2021-06-22 06:14 UTC, nik-redhat commented on common/ops/gluster_ops/auth_ops.py
> +Auth ops module deals with the aut allow and reject operations
nit: auth

2021-06-22 06:14 UTC, nik-redhat commented on common/ops/gluster_ops/auth_ops.py
> +        if ret['error_code'] == 0 and self.verify_auth_allow(volname,
You can ignore the check of error_code here, as it will be done inside abstract ops, or if we want to do it here and don't raise an exception on failure, pass `False` by default to the `excep` arg.

2021-06-22 06:14 UTC, nik-redhat commented on common/ops/gluster_ops/auth_ops.py
> +        if ret['error_code'] == 0 and self.verify_auth_reject(volname,
Same as above

2021-06-22 07:10 UTC, aujjwal-redhat commented on common/ops/gluster_ops/auth_ops.py
> +Auth ops module deals with the aut allow and reject operations
Ack

2021-06-22 07:11 UTC, aujjwal-redhat commented on common/ops/gluster_ops/auth_ops.py
> +        if ret['error_code'] == 0 and self.verify_auth_allow(volname,
Yeah true.

2021-06-22 07:11 UTC, aujjwal-redhat commented on common/ops/gluster_ops/auth_ops.py
> +        if ret['error_code'] == 0 and self.verify_auth_reject(volname,
Ack

2021-06-22 08:33 UTC, aujjwal-redhat commented
```js
 test_vol_ops
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     rep     |     PASS    | 20.355896472930908 |
|     dist    |     PASS    | 21.318906784057617 |
|     disp    |     PASS    | 17.63235068321228  |
|     arb     |     PASS    | 18.826939344406128 |
|   dist-rep  |     PASS    | 23.72915816307068  |
|   dist-arb  |     PASS    | 25.265827655792236 |
|  dist-disp  |     PASS    | 20.335372924804688 |
+-------------+-------------+--------------------+

```

2021-06-23 08:04 UTC, nik-redhat approved these changes

2021-06-23 08:14 UTC, merged