Added heal ops
srijan-sivakumar/redant pull request #692
Opened 2021-06-23 07:08 UTC by aujjwal-redhat

Added:
* monitor_heal_completion
* is_heal_complete
* is_volume_in_split_brain

Fixes: #691

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-23 11:19 UTC, aujjwal-redhat commented
```js
 test_heal_ops
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     arb     |     PASS    | 14.49189805984497  |
|     rep     |     PASS    | 15.000241756439209 |
|   dist-rep  |     PASS    | 15.69334101676941  |
|   dist-arb  |     PASS    | 17.532535552978516 |
+-------------+-------------+--------------------+

```

2021-06-23 12:02 UTC, nik-redhat requested changes

2021-06-23 12:02 UTC, nik-redhat commented on tests/example/sample_component/test_heal_ops.py
> +            raise Exception("Volume in split-brain")
Good to have some actual healing being done on the volume to have the ops more _fail proof_

2021-06-23 12:06 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +    def get_heal_info(self, node: str, volname: str):
Ack

2021-06-23 12:06 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                heal_info data per brick.
Ack

2021-06-23 12:06 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +        if ret['msg']['opRet'] != '0':
Yeah true.

2021-06-23 12:06 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                                interval_check=120) -> bool:
Ack

2021-06-23 12:06 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                break
Ack

2021-06-23 12:06 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            heal_complete = True
Yeah that's better

2021-06-23 12:07 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +    def get_heal_info_split_brain(self, node: str, volname: str):
Ack

2021-06-23 12:07 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +        if ret['msg']['opRet'] != '0':
Yeah true.

2021-06-23 12:07 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +    def is_volume_in_split_brain(self, node: str, volname: str):
Ack

2021-06-23 12:08 UTC, aujjwal-redhat commented on tests/example/sample_component/test_heal_ops.py
> +            raise Exception("Volume in split-brain")
Like, how exactly can we check? :-|

2021-06-23 12:21 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                break
@nik-redhat I think the logic here is fine. 
The bricks are traversed and checked if any one (at least) is not yet healed. In case it is not healed yet heal_complete = False and then it will check outside.

If we go with the above logic, even if one of the brick is healed, heal_complete will be True and will break. Other bricks in that case wont be checked.

What we can do is put a break after heal_complete=False. 
Lemme know what you think : )

2021-06-23 12:41 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                break
Ahh...right. I missed the second `for` loop above.
Yes, adding a `break` would help fail early.

2021-06-23 15:36 UTC, aujjwal-redhat commented
```js

 test_heal_ops
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|     rep     |     PASS    | 144.2814235687256 |
+-------------+-------------+-------------------+

```

2021-06-24 05:42 UTC, nik-redhat approved these changes
Good one.

2021-06-24 10:35 UTC, merged