Added daemon related functions in heal ops
srijan-sivakumar/redant pull request #702
Opened 2021-06-24 12:57 UTC by aujjwal-redhat

Added:
1. is_shd_daemon_running
2. is_shd_daemonized
3. get_heal_info_summary
4. get_self_heal_daemon_pid

Fixes: #700

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-25 07:13 UTC, aujjwal-redhat commented
```js

 test_heal_ops
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     rep     |     PASS    | 145.49896430969238 |
+-------------+-------------+--------------------+

 vol_destroy_test
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|     rep     |     PASS    | 9.297699213027954 |
+-------------+-------------+-------------------+
```

2021-06-25 07:44 UTC, nik-redhat requested changes

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            mnode : Node on which commands are executed
nit: node

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            if result['error_code'] == 0:
If you are checking it here, pass `exep=False` above to abstract ops.

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            ret = self.get_self_heal_daemon_pid(nodes)
Shouldn't the return value be received like `ret, _ = self.get....`?

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                flag = 1
Is another `flag` variable needed? We can use `ret` later on as well, right?

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            return False
Let's change the last return to `return ret` after following the comments above. That should do as well.

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +    def is_shd_daemon_running(self, mnode: str,
For consistency, keep it `node`.

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                              node: str, volname: str) -> bool:
And make this `node` -> `server`

2021-06-25 07:44 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            node (str): The node to be checked for whether
As per the above change.

2021-06-25 07:47 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            mnode : Node on which commands are executed
Ack

2021-06-25 07:47 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            if result['error_code'] == 0:
Ack

2021-06-25 07:49 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            ret = self.get_self_heal_daemon_pid(nodes)
Yeah, true. Actually,

2021-06-25 07:50 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                flag = 1
Yeah

2021-06-25 07:51 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                              node: str, volname: str) -> bool:
ok

2021-06-25 07:58 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +            return False
yeah that's better

2021-06-25 08:08 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +    def is_shd_daemon_running(self, mnode: str,
Ack

2021-06-28 10:01 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                    if not (result['msg'][0]).strip().rstrip("\n"):
Are both of the `strip` functions needed?

2021-06-28 10:36 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                    if not (result['msg'][0]).strip().rstrip("\n"):
Just considering the worst case like "             xyz\n          " XD

2021-06-28 10:41 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +                    if not (result['msg'][0]).strip().rstrip("\n"):
Ack!

2021-06-28 10:42 UTC, nik-redhat approved these changes

2021-06-28 10:43 UTC, merged