Adding the Parsing module
srijan-sivakumar/redant pull request #71
Opened 2021-03-15 09:15 UTC by nishith-vihar

Containes Parser and ParamsHandler along with config file.
gluster_test_main is also added. Readme is attached which
shows how to invoke gluster_test_main.

Fixes: #70
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

### All Submissions:

Desciption:

(If it closes the issue)
Fixes: #
(If it just updates the Issue)
Updates: #

2021-03-15 09:30 UTC, nishith-vihar commented
Sorry about the PR message. I forgot to remove the template comments

2021-03-15 09:30 UTC, nik-redhat commented
Please update the commit-msg as per the template.

2021-03-15 09:37 UTC, nik-redhat commented on parsing/gluster_params_handler.py
> +        Gives the server ip given the server name
Since you are explaining what this function returns, this line is not required.
Update in other functions as well.

2021-03-15 09:38 UTC, nik-redhat commented on parsing/gluster_params_handler.py
> +        Gives the server ip given the server name
Or, rather keep it but modify the return `docstring` a bit to be differentiatied.

2021-03-15 09:40 UTC, nik-redhat commented on parsing/gluster_params_handler.py
> +        Gives the server ip given the server name
For example:
```
def get_all_bricks(mnode, volname):
    """Get list of all the bricks of the specified volume.

    Args:
        mnode (str): Node on which command has to be executed
        volname (str): Name of the volume

    Returns:
        list: List of all the bricks of the volume on Success.
        NoneType: None on failure.
    """
```

2021-03-15 09:43 UTC, nik-redhat commented on parsing/gluster_params_handler.py
> +            ilist of brick root of the given server
Typo: list

2021-03-15 10:43 UTC, nishith-vihar commented on parsing/gluster_test_main.py
> +    main()
Yeah this is fine actually

2021-03-15 11:04 UTC, nik-redhat commented
Looks good, but let's wait for Srijan's review for the config file structure.

2021-03-16 04:29 UTC, srijan-sivakumar requested changes

2021-03-16 04:29 UTC, srijan-sivakumar commented on parsing/config.yml
> +        platform: 'windows'
I'm not sure we are supporting windows right out of the box. Maybe make it linux based distro.

2021-03-16 04:29 UTC, srijan-sivakumar commented on parsing/config.yml
> +        platform: 'windows'
This is wrt this test framework. Glusterfs can be mounted and used by Windows client. But for now, let's focus on nix based clients.

2021-03-16 04:29 UTC, srijan-sivakumar commented on parsing/README.md
> +> python3 gluster_test_main.py -c <<-path to config file->>
instead of `gluster_test_main.py`, maybe we can name it inline with the framework name and test_runner. So something like `redant_test_runner.py`

2021-03-16 04:29 UTC, srijan-sivakumar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
Too many levels of calling and execution. If we go by this then the flow would be, gluster_test_main -> test_runner -> runner_thread wherein the test runner would just get the list of all tests and it'll invoke the runner_thread. test_runner then just feels like an extra level being added in here. Parsing, Test list preparation and invocation of runner thread accordingly should be inside the test_runner.py.

2021-03-16 04:29 UTC, srijan-sivakumar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
In this manner, this will become our test runner. Why to add one extra level of abstraction ? Any particular reason behind it ?

2021-03-16 04:31 UTC, srijan-sivakumar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
One more point, if this is the script to be called at the very beginning, it should be at the base directory of the project an not inside the parsing.

2021-03-16 07:33 UTC, nishith-vihar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
> Too many levels of calling and execution. If we go by this then the flow would be, gluster_test_main -> test_runner -> runner_thread wherein the test runner would just get the list of all tests and it'll invoke the runner_thread. test_runner then just feels like an extra level being added in here. Parsing, Test list preparation and invocation of runner thread accordingly should be inside the test_runner.py.

Actually according to the design doc there are both test_runner and a test_main but for now i can make the main as test_runner

2021-03-16 07:39 UTC, srijan-sivakumar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
Cool, but what are your thoughts ? Do we actually see a need for another module being invoked in between which would just read the list and call runner_thread or should the test_main and test_runner be fused into one module to handle the same?

2021-03-16 07:53 UTC, nishith-vihar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
> Cool, but what are your thoughts ? Do we actually see a need for another module being invoked in between which would just read the list and call runner_thread or should the test_main and test_runner be fused into one module to handle the same?

At this point of time i am not sure about how multiple threads will be handled. If the test_runner only invokes threads then i guess there is no need for an extra layer but if it has to handle some other cases in case of multiple threads then maybe a seperate module for running threads would be fine.

2021-03-16 07:57 UTC, srijan-sivakumar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
Firstly, I think the nomenclature is still problematic. The runner_thread won't be executed as a thread. If we had to deal with threads, python would be the last place to create a solution into. The runner_thread would be invoked as a exec function from within the test_runner and then passed on the parameters. So basically a standard way of how parent and child process functions in linux.

2021-03-16 08:00 UTC, nishith-vihar commented on parsing/gluster_test_main.py
> +3) Invocation of the component which manages test execution (test_runner).
Got that

2021-03-16 08:13 UTC, srijan-sivakumar requested changes
Better to add a readme supporting the config file and as to what all goes into the config file and what all information needs to be added by a user who's going to use this framework.

2021-03-16 08:13 UTC, srijan-sivakumar commented on parsing/config.yml
> +    - &server_vm1 server-vm1
maybe you can add examples for the configurations which need to be added in a comment. For now we might be able to understand as to what goes where but down the line, for people starting out, this config file will be a maze and difficult to tame without examples.

2021-03-16 08:13 UTC, srijan-sivakumar commented on parsing/README.md
> +> python3 gluster_test_main.py -c <<-path to config file->>
`redant_test_runner.py` ?

2021-03-16 12:23 UTC, aujjwal-redhat commented on redant_test_runner.py
> +3) Invocation of the runner_thread which runs the testcase.
Invocation of test runner right? Or are we going to perform the test runner work also in this ?

2021-03-16 12:37 UTC, nishith-vihar commented on redant_test_runner.py
> +3) Invocation of the runner_thread which runs the testcase.
As of now we are don't have a seperate component as test_runner and the gluster_test_main in design doc is renamed as redant_test_runner and this component will directly bring up threads using runner_thread.

2021-03-16 12:38 UTC, aujjwal-redhat commented on redant_test_runner.py
> +3) Invocation of the runner_thread which runs the testcase.
Ack.

2021-03-17 06:32 UTC, srijan-sivakumar commented on parsing/CONFIG_README.md
> +ip address in the further config file or in the test cases. 1 should be replaced
Nit, instead of `1`, `one`

2021-03-17 06:35 UTC, srijan-sivakumar reviewed
Would the server and client credentials be mentioned in this config file ? Or would that be a different config file..

2021-03-17 07:22 UTC, nishith-vihar commented
> Would the server and client credentials be mentioned in this config file ? Or would that be a different config file..

But Actually barak had said that the user has to insert only the ip. is there any idea of implementing a passwordless ssh or do we continue with credentials. I think even glusto does not take any credentials other than ip for ssh

2021-03-17 07:46 UTC, srijan-sivakumar commented
Hmm..ok. We can go by the passwordless ssh manner also, That would work. It's just that the user would have to set it up by themselves. It is but an one time activity. But I feel, we should be having the mechanism to accept password based connections too. Or we can make it a strict passwordless ssh only manner. @nishith-vihar , @neesingh-rh , @aujjwal-redhat , @nik-redhat  and @BarakSason  what are your thoughts on this ? Should we enforce passwordless ssh or keep it both passwordless ssh as well as authentication with password with every ssh.

2021-03-17 08:25 UTC, nik-redhat commented
I think the passwordless ssh approach would be better.
But, to have a flexible framework if we can accommodate both, would be great!

2021-03-17 08:31 UTC, aujjwal-redhat commented
> I think the passwordless ssh approach would be better.
> But, to have a flexible framework if we can accommodate both, would be great!

Yeah I would suggest the same.

2021-03-17 10:05 UTC, nishith-vihar commented
I have added the credentials for one server and client just for example for now and can be removed safely once passwordless ssh has been implemented

2021-03-17 13:52 UTC, srijan-sivakumar approved these changes

2021-03-17 13:53 UTC, srijan-sivakumar commented
LGTM. But we need to take this up and fine tune as we move ahead.

2021-03-17 13:53 UTC, merged