Added heal ops required for arbiter
srijan-sivakumar/redant pull request #729
Opened 2021-06-29 09:18 UTC by aujjwal-redhat

Added the following heal ops:
* enable_self_heal_daemon
* disable_self_heal_daemon
* do_bricks_exist_in_shd_volfile

Fixes: #728

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-29 12:29 UTC, aujjwal-redhat commented
```sh
 test_heal_ops
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:02:31       |     N/A     |
+-------------+-------------+-----------------------+-------------+

```

2021-06-29 12:36 UTC, srijan-sivakumar submitted a review, later dismissed

2021-06-29 12:36 UTC, srijan-sivakumar commented on common/ops/gluster_ops/heal_ops.py
> +                                       path: str = None) -> bool:
The path shouldn't be asked from the user. With the help of the volume name, we can create the path here itself.

2021-06-29 12:36 UTC, srijan-sivakumar commented on common/ops/gluster_ops/heal_ops.py
> +        self.logger.info(f"Brick List from volume "
I think we can keep this log as debug. Same for the one following this.

2021-06-29 12:36 UTC, srijan-sivakumar commented on tests/example/sample_component/test_heal_ops.py
> +        path = (f"/var/lib/glusterd/vols/{self.vol_name}/"
As mentioned, path of volfile should be generated dynamically using the volname in the ops function rather than being passed from the test case by the user.

2021-06-29 12:38 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +        self.logger.info(f"Brick List from volume "
Ack

2021-06-29 12:39 UTC, aujjwal-redhat commented on tests/example/sample_component/test_heal_ops.py
> +        path = (f"/var/lib/glusterd/vols/{self.vol_name}/"
Oh I thought by dynamic path you meant giving user the control over the path. Will change that.

2021-06-29 12:47 UTC, aujjwal-redhat commented
```sh

 test_heal_ops
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:02:29       |     N/A     |
+-------------+-------------+-----------------------+-------------+
```

2021-06-29 13:08 UTC, nik-redhat requested changes

2021-06-29 13:08 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +        if ret['error_code'] != 0:
I doubt if `error_code` will contain the correct value here because there are a lot of places where the error_code is not updated by Gluster. So, better to execute the above command with `--xml` flag and check for `ret['msg']['opRet']` over here.

2021-06-29 13:08 UTC, nik-redhat commented on common/ops/gluster_ops/heal_ops.py
> +        ret = self.execute_abstract_op_node(cmd, node, False)
Same as above

2021-06-30 05:08 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +        if ret['error_code'] != 0:
Ack

2021-06-30 05:08 UTC, aujjwal-redhat commented on common/ops/gluster_ops/heal_ops.py
> +        ret = self.execute_abstract_op_node(cmd, node, False)
Ack

2021-06-30 06:17 UTC, nik-redhat approved these changes

2021-06-30 06:18 UTC, merged