[Core] Sanitize enhancement for change in volume brick counts
srijan-sivakumar/redant pull request #733
Opened 2021-06-29 16:17 UTC by srijan-sivakumar

This addition will allow test cases modifying the
volume configuration on brick level to be made
non disruptive.

Fixes: #732

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

2021-06-29 16:59 UTC, nik-redhat requested changes

2021-06-29 16:59 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +            self.cleanup_volume(volname, server_list[0])
After the cleanup, the brick paths also need to be deleted, before we could reuse them.

2021-06-29 16:59 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +        if dist_count is None and dist_count is None:
nit: replica_count

2021-06-30 08:09 UTC, srijan-sivakumar commented
> After the cleanup, the brick paths also need to be deleted, before we could reuse them. 

Ack.

2021-06-30 08:09 UTC, srijan-sivakumar commented
> nit: replica_count 

Ack

2021-06-30 09:49 UTC, nik-redhat approved these changes

2021-06-30 09:50 UTC, merged