Migrated test_cyclic_brick_kill_list
srijan-sivakumar/redant pull request #738
Opened 2021-06-30 07:50 UTC by aujjwal-redhat

Migrated the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/brick_cases/test_cyclic_brick_kill_list.py)

Updates: #292

Fixes: #734

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-06-30 08:28 UTC, aujjwal-redhat commented
```sh
Table:
 test_cyclic_brick_kill_list
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:05:42       |     N/A     |
|   dist-rep  |     PASS    |        00:11:20       |     N/A     |
+-------------+-------------+-----------------------+-------------+

Framework runtime : 00 hours 17 minutes 12 seconds
```

2021-07-01 09:13 UTC, srijan-sivakumar requested changes

2021-07-01 09:13 UTC, srijan-sivakumar commented on tests/functional/arbiter/brick_cases/test_cyclic_brick_kill_list.py
> +        ret = redant.validate_io_procs(self.list_of_procs, self.mnt_list)
Internally validate_io_procs is checking if the async process has completed or not and waits till it is completed. But this isn't desired here. We just need to verify that the IO hasn't ended before starting with the kill brick and restart brick operation. But with the current logic in `validate_io_procs` the validation would mean either the IO is completed or IO failed. There's no status for IO is going on.. We do have a function in rexe called check_async_command_status which checks if the async operation has been completed or not. This would be a better candidate here than `validate_io_procs`.

2021-07-02 05:23 UTC, aujjwal-redhat commented on tests/functional/arbiter/brick_cases/test_cyclic_brick_kill_list.py
> +        ret = redant.validate_io_procs(self.list_of_procs, self.mnt_list)
Ack

2021-07-02 09:16 UTC, aujjwal-redhat commented
```sh
+---------------+-------+--------------+
Table:
 test_cyclic_brick_kill_list
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:05:42       |     N/A     |
|   dist-rep  |     PASS    |        00:11:12       |     N/A     |
+-------------+-------------+-----------------------+-------------+

Framework runtime : 00 hours 17 minutes 02 seconds

✔ Tearing down successful.
```

2021-07-02 13:59 UTC, srijan-sivakumar approved these changes

2021-07-02 13:59 UTC, merged