Ops: Added shrink_volume op
srijan-sivakumar/redant pull request #739
Opened 2021-06-30 09:37 UTC by nik-redhat

### All Submissions:

Description:
Added the shrink_volume and form_brick_list_to_remove_bricks op

Fixes: #736

Signed-off-by: nik-redhat <nladha@redhat.com>

2021-07-01 07:34 UTC, nik-redhat commented
Test run:
```
Table:
 test_expand_shrink_volume
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:00:47       |     N/A     |
|     rep     |     PASS    |        00:01:08       |     N/A     |
|   dist-rep  |     PASS    |        00:01:15       |     N/A     |
|     arb     |     PASS    |        00:01:09       |     N/A     |
|   dist-arb  |     PASS    |        00:01:15       |     N/A     |
|     disp    |     PASS    |        00:02:07       |     N/A     |
|  dist-disp  |     PASS    |        00:02:23       |     N/A     |
+-------------+-------------+-----------------------+-------------+



Framework runtime : 00 hours 10 minutes 18 seconds
```

2021-07-01 08:55 UTC, srijan-sivakumar requested changes

2021-07-01 08:55 UTC, srijan-sivakumar commented on common/ops/gluster_ops/volume_ops.py
> +                self.es.remove_val_from_cleands(node, brick_dir)
We might also need to handle the changes to the volume counts, i.e. rep_count, dist_count etc in environ..

2021-07-01 09:21 UTC, nik-redhat commented on common/ops/gluster_ops/volume_ops.py
> +                self.es.remove_val_from_cleands(node, brick_dir)
Yeah, will add that.

2021-07-01 11:36 UTC, nik-redhat commented
Test run:
```
Table:
 test_expand_shrink_volume
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:01       |     N/A     |
|     dist    |     PASS    |        00:00:54       |     N/A     |
|   dist-rep  |     PASS    |        00:01:16       |     N/A     |
|     arb     |     PASS    |        00:01:09       |     N/A     |
|   dist-arb  |     PASS    |        00:01:15       |     N/A     |
|     disp    |     PASS    |        00:02:10       |     N/A     |
|  dist-disp  |     PASS    |        00:02:20       |     N/A     |
+-------------+-------------+-----------------------+-------------+



Framework runtime : 00 hours 10 minutes 19 seconds
```

2021-07-02 12:09 UTC, nik-redhat commented
I think we are good to take in this PR as well?

2021-07-02 12:17 UTC, aujjwal-redhat approved these changes
LGTM

2021-07-02 14:11 UTC, srijan-sivakumar approved these changes

2021-07-02 14:11 UTC, merged