Migrated TC test_glusterd_statedump_with_server_client_quorum
srijan-sivakumar/redant pull request #744
Opened 2021-07-01 10:54 UTC by nik-redhat

Migrated TC [test_glusterd_statedump_with_server_client_quorum](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py)

Fixes: #741 

Signed-off-by: nik-redhat <nladha@redhat.com>

2021-07-01 10:56 UTC, nik-redhat commented
Test run:
```
Table:
 test_glusterd_statedump
 
+-------------+-------------+-----------------------+-----------------------------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) |            Skip Reason            |
+-------------+-------------+-----------------------+-----------------------------------+
|     rep     |     None    |        00:00:21       | Server/Brick requirements not met |
|   dist-rep  |     None    |        00:00:32       | Server/Brick requirements not met |
+-------------+-------------+-----------------------+-----------------------------------+



Framework runtime : 00 hours 01 minutes 03 seconds
```

I did test up to the part where it can be run with 3 servers and adding the result for that below:
```
Table:
 test_glusterd_statedump
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:44       |     N/A     |
|   dist-rep  |     PASS    |        00:00:53       |     N/A     |
+-------------+-------------+-----------------------+-------------+


Framework runtime : 00 hours 01 minutes 46 seconds
```

2021-07-01 11:06 UTC, srijan-sivakumar commented
woah..we need 5 servers for this...

2021-07-01 16:53 UTC, srijan-sivakumar commented
After running in a 6 server environment.

```console
[root@dhcp42-44 redant]# python3 core/redant_main.py -c ../config.yml -t tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py -ll D
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_glusterd_statedump_with_server_and_client_quorum_set-rep
✖ test_glusterd_statedump_with_server_and_client_quorum_set-rep Failed
✔ Running test case : test_glusterd_statedump_with_server_and_client_quorum_set-dist-rep
✖ test_glusterd_statedump_with_server_and_client_quorum_set-dist-rep Failed
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |     0.0      |
|    Skipped    |   0   |      0       |
|     Total     |   1   |     0.0      |
+---------------+-------+--------------+
Table:
 test_glusterd_statedump_with_server_and_client_quorum_set
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     FAIL    |        00:00:44       |     N/A     |
|   dist-rep  |     FAIL    |        00:01:11       |     N/A     |
+-------------+-------------+-----------------------+-------------+



Framework runtime : 00 hours 02 minutes 14 seconds

✔ Tearing down successful.
```

2021-07-02 11:03 UTC, nik-redhat commented
@srijan-sivakumar give it a try now...

2021-07-02 11:07 UTC, srijan-sivakumar commented
> @srijan-sivakumar give it a try now...

Ack..will check it out.

2021-07-02 13:40 UTC, srijan-sivakumar requested changes

2021-07-02 13:40 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
> +        self.assertTrue(ret, "Failed to create and start the volume: %s"
We might need to replace this... `assertTrue` is a legacy from glusto...

2021-07-02 13:46 UTC, nik-redhat commented on tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
> +        self.assertTrue(ret, "Failed to create and start the volume: %s"
Ahh, I think it got left out :p

2021-07-02 14:07 UTC, srijan-sivakumar reviewed
I saw one more function call...pushing the change as I'm already on that branch locally :p

2021-07-02 14:07 UTC, srijan-sivakumar commented on tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
> +        self.set_volume_options(self.volname, option, self.server_list[0])
ahh..missed it before...this would be `redant.set_volume_options`

2021-07-02 14:12 UTC, srijan-sivakumar approved these changes

2021-07-02 14:12 UTC, srijan-sivakumar commented
Waiting for the CI run to finish..though code wise things LGTM

2021-07-02 14:13 UTC, srijan-sivakumar commented
```console
[root@dhcp42-44 redant]# python3 core/redant_main.py -c ../config.yml -t tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py -ll D
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_glusterd_statedump_with_server_and_client_quorum_set-rep
✔ test_glusterd_statedump_with_server_and_client_quorum_set-rep Succeeded
✔ Running test case : test_glusterd_statedump_with_server_and_client_quorum_set-dist-rep
✔ test_glusterd_statedump_with_server_and_client_quorum_set-dist-rep Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|    Skipped    |   0   |      0       |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_glusterd_statedump_with_server_and_client_quorum_set
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:49       |     N/A     |
|   dist-rep  |     PASS    |        00:02:25       |     N/A     |
+-------------+-------------+-----------------------+-------------+



Framework runtime : 00 hours 04 minutes 34 seconds

✔ Tearing down successful.```

2021-07-02 14:13 UTC, merged