[Core][Common] Snap ops addition
srijan-sivakumar/redant pull request #755
Opened 2021-07-03 09:01 UTC by srijan-sivakumar

### All Submissions:

Desciption: Addition of snapshot ops.

(If it closes the issue)
Fixes: #706

2021-07-05 17:18 UTC, srijan-sivakumar commented
@nik-redhat @aujjwal-redhat This test definitely needs a CI run on complete suite. Will test it tomorrow and see if things work fine.

2021-07-06 12:59 UTC, srijan-sivakumar commented
```console
Summary:
+---------------+-------+-------------------+
|    Category   | Cases |    Pass Percent   |
+---------------+-------+-------------------+
| nonDisruptive |   24  | 86.11111111111111 |
|   Disruptive  |   74  | 78.28571428571428 |
|    Skipped    |   2   |         0         |
|     Total     |   98  |  80.5668016194332 |
+---------------+-------+-------------------+
```

The changes are in-line with our CI run data after changes too. @nik-redhat @aujjwal-redhat , over to you guys for reviewing 😛

2021-07-06 13:12 UTC, aujjwal-redhat requested changes

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        cmd = (f"gluster snapshot restore {snapname} --mode=script --xml")
nit: ( ) not needed

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +# Start the volume
nit: indentation

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +            cmd = (f"gluster snapshot status {snapname} --mode=script --xml")
nit: ( ) not needed

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +            cmd = (f"gluster snapshot info {snapname} --mode=script --xml")
same as above

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        return self.execute_abstract_op_node(cmd, node, excep)
indentation doesn't look right. : \

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        cmd = (f"gluster snapshot volume {volname} --xml --mode=script")
same as above

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        cmd = (f"gluster snapshot deactivate {snapname} --mode=script --xml")
same as above

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
>          """
docstring doesn't match the param list

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/gluster_ops/volume_ops.py
> +                        cmd = (f"stat {mount}")
( ) not needed

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/support_ops/machine_ops.py
>      def reload_glusterd_service(self, node):
node : str

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/support_ops/machine_ops.py
>      def reload_glusterd_service(self, node):
return type missing

2021-07-06 13:12 UTC, aujjwal-redhat commented on common/ops/support_ops/machine_ops.py
> +            node (str): Node whose LV path detail is required.
nodes (list | str)

Moreover, we can take nodes: str as the param and check if not isinstance(nodes, list), convert to list and continue

2021-07-06 13:12 UTC, aujjwal-redhat commented on tests/example/sample_component/test_snap_ops.py
> +
Redant has also mutated to its delta variant i assume XD

2021-07-07 03:53 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +        cmd = (f"gluster snapshot restore {snapname} --mode=script --xml")
Just following a standard code practice.. I guess we can live with that 😛

2021-07-07 03:54 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +        return self.execute_abstract_op_node(cmd, node, excep)
It is actually compliant with how python works. When using IDEs, the IDE can take charge on properly indenting according to the rules.

2021-07-07 03:55 UTC, srijan-sivakumar commented on common/ops/support_ops/machine_ops.py
>      def reload_glusterd_service(self, node):
@aujjwal-redhat this is not even part of my current patch... 😄 ...

2021-07-07 03:56 UTC, srijan-sivakumar commented on tests/example/sample_component/test_snap_ops.py
> +
😆 I guess this was missed during testing.

2021-07-07 03:57 UTC, srijan-sivakumar commented on common/ops/support_ops/machine_ops.py
> +            node (str): Node whose LV path detail is required.
Ack.

2021-07-07 04:44 UTC, aujjwal-redhat approved these changes
LGTM

2021-07-07 05:53 UTC, nik-redhat requested changes

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        if ret['msg']['opRet'] != 0:
We should only check this if `excep=False`

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        self.volume_stop(volname, node, force=True)
Is it necessary for volume to be stopped using force?

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        self.volume_start(volname, node, force=True)
Same as above

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        self.volume_stop(volname, node, force=True)
If not then we should do a fail check here as well, by passing `excep=False` by default inside this function.

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +    def get_snap_status(self, node: str) -> dict:
Having `excep` as a param will help us to have a TC for line coverage check, in case of `Wrong` values.

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        return {}
We can simply return None as well?

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        return {}
Because `{} is not None` if I am not wrong.

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +            ret: A dictionary consisting of snap info.
nit: Or None in case of failure

2021-07-07 05:53 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        return {}
Better to return `None`.

2021-07-07 05:53 UTC, nik-redhat commented on core/environ.py
> +        self.cleands = {}
cleands is no more needed.

2021-07-08 03:16 UTC, srijan-sivakumar commented on core/environ.py
> +        self.cleands = {}
Ack.

2021-07-08 03:17 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +    def get_snap_status(self, node: str) -> dict:
Ack. Will add that in here.

2021-07-08 03:18 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +            ret: A dictionary consisting of snap info.
Ack.

2021-07-08 03:20 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +        self.volume_stop(volname, node, force=True)
Well, the focus here is on the snap_restore when volume is stopped. Hence it is better to use force. Now we can make this configurable of whether to give force option or not. But seeing the test cases, I don't see a need to add one more param. We can modify on future if it needs to be configurable.

2021-07-08 03:20 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +        if ret['msg']['opRet'] != 0:
Ahh..yes.

2021-07-08 05:48 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        self.volume_stop(volname, node, force=True)
I mean functionality-wise we shouldn't be doing a stop and start with force, that way we can bypass few errors in the code. Better to check the return value of the stop and start function call by passing `excep=False` to the function and return `False` from the caller i.e, `snashot_restore_complete` in case of failure.

2021-07-08 06:28 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +        self.volume_stop(volname, node, force=True)
Cool, we can remove the force, but for excep, we should be taking the value user has passed. If the user doesn't want a return value specially if things fail, we can let it fail in case of volume start/stop itself.

2021-07-08 09:34 UTC, nik-redhat commented on common/ops/gluster_ops/snapshot_ops.py
> +        if not excep and ret['msg']['opRet'] != 0:
nit: `0` should be within ' '. We get a string :p
Same for below checks as well

2021-07-08 10:09 UTC, srijan-sivakumar commented on common/ops/gluster_ops/snapshot_ops.py
> +        if not excep and ret['msg']['opRet'] != 0:
Ack :)

2021-07-08 10:16 UTC, nik-redhat approved these changes

2021-07-08 10:16 UTC, merged