Added parent_test
srijan-sivakumar/redant pull request #76
Opened 2021-03-15 14:33 UTC by aujjwal-redhat

Started working on parent_test
Created the basic functions and added the standard info.

Updates: #75

Signed-off-by: aujjwal-redhat <aujjwal@redhat.com>

2021-03-16 04:33 UTC, srijan-sivakumar requested changes

2021-03-16 04:33 UTC, srijan-sivakumar commented on parent_test.py
> +    def core_init(self):
Not required.

2021-03-16 04:33 UTC, srijan-sivakumar commented on parent_test.py
> +    def core_init(self):
This is taken care in runner_thread itself.

2021-03-16 04:37 UTC, aujjwal-redhat commented on parent_test.py
> +    def core_init(self):
Ok. Will remove it then.

2021-03-16 07:17 UTC, aujjwal-redhat commented on parent_test.py
> +from abc import ABC
abstract class

2021-03-16 07:18 UTC, srijan-sivakumar commented on parent_test.py
> +from abc import ABC
Also, do add a module doc, addressing as to what is happening in here.

2021-03-16 07:18 UTC, aujjwal-redhat commented on parent_test.py
> +class Parent_Test(ABC):
@srijan-sivakumar here I am extending abstract class properties.

2021-03-16 07:18 UTC, srijan-sivakumar commented on parent_test.py
> +class Parent_Test(ABC):
Ack.

2021-03-16 07:54 UTC, srijan-sivakumar requested changes

2021-03-16 07:54 UTC, srijan-sivakumar commented on parent_test.py
> +        Deletes the volume
let's not say volume as there are TCs which won;t even be creating volumes.

2021-03-16 07:54 UTC, srijan-sivakumar commented on parent_test.py
> +        Creates volume
Same as below. Volume creation is not in purview in every TC. Let's just say initialization before the TC func is run.

2021-03-16 07:54 UTC, srijan-sivakumar commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
why does mixin need the parent class ? It is the test cases which would need the parent test to be inherited right?

2021-03-16 07:57 UTC, aujjwal-redhat commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
Yeah true

2021-03-16 07:59 UTC, aujjwal-redhat commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
So should I import the logging module inside the parent class only ? I added it in redant_mixin to use the logging specifically.

2021-03-16 08:01 UTC, srijan-sivakumar commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
We can safely remove the logging from the abstract class. If at all any user needs logging that the TC has been started that can be overridden inside the child class. Also, each TC will have it's own logging file so, there won't be any confusion as to when the logs pertaining to a certain TC start and end.

2021-03-16 08:06 UTC, aujjwal-redhat commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
If we remove logging from abstract class then how will we show init() and terminate() function executed?

```js
self.rlog(f"{self.TEST_NAME} from {self.COMPONENT} inits")
```

2021-03-16 08:15 UTC, srijan-sivakumar commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
technically, do we need to show them being executed ? Because the only thing we can do is invoke the init and terminate of the child class and call the init and child of it's super ( parent ), in this way we don't need logging to be added as part of the parent class

2021-03-16 08:16 UTC, srijan-sivakumar commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
Also, what all operations do you think can generically be part of the init and terminate in the parent class ?

2021-03-16 08:26 UTC, aujjwal-redhat commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
> technically, do we need to show them being executed ? Because the only thing we can do is invoke the init and terminate of the child class and call the init and child of it's super ( parent ), in this way we don't need logging to be added as part of the parent class

> Also, what all operations do you think can generically be part of the init and terminate in the parent class ?

init operation must consist of starting gluster in the server
since few operations like peer ops don't need volume to be created so even I feel volume creation should not be part of init.

But if gluster didn't start because of some issue then we will need logging ryt?

2021-03-16 08:32 UTC, srijan-sivakumar commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
So, here's the thing. We will be running tests parallely in a cluster. So, by doing starting or stopping glusterfs inside init and terminate, we'd be disruption the whole env. This should be part of the TC. Secondly, the order in which the TC will be run will be helpful to not do certain checks again and again. Why do we have to re-create volumes again and again if the test is about something else altogether. Same goes for glusterd start and stop. Technically, they'd be part of a TC body and not init and terminate. In giving init and terminate so much functionality, we are repeating what past framework has been doing so, where do we save the compute and resource here ?

2021-03-16 08:33 UTC, srijan-sivakumar commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
@nik-redhat what's your thought on this ?

2021-03-16 08:36 UTC, aujjwal-redhat commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
Then why do we need the parent test class to be abstract ?

2021-03-16 08:39 UTC, aujjwal-redhat commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
I think there is a confusion coz what we have received as input from the java demo in prev to prev meet says this:
```

	public void core_init() {
		// Init logger
		// Init ssh connection
	}

	public void init() {
		core_init();
		// Create connection
		// Create volume
		System.out.println(test_name + " from component " + component + " inits");
	}

	public void terminate() {
		// Delete volume
		// Close connection
		System.out.println(test_name + " terminates");
	}
}
```

2021-03-16 08:46 UTC, aujjwal-redhat commented on redant_libs/redant_mixin.py
> +from parent_test import Parent_Test
Even rhe doc says this:
```
parent_test (5) - This component contains all common functionality and data which is required by all tests. 
This component inherits functionality from the components in the next sections.
Examples of shared functionality and data may be:
* Implementation of init and terminate methods which create and destroy the environment in which the test operates
* Variables to contain common data such as test name, whether this test can run parallely to other tests, test result, etc’
```

Let's discuss this in the meet.

2021-03-22 08:31 UTC, aujjwal-redhat commented on parent_test.py
> +        self. TEST_NAME = test_name
Yeah true

2021-03-22 08:31 UTC, aujjwal-redhat commented on parent_test.py
> +    def init(self):
Yeah. Will remove it.

2021-03-22 08:32 UTC, aujjwal-redhat commented on parent_test.py
> +    PASS: bool
Yeah.

2021-03-22 08:34 UTC, aujjwal-redhat commented on parent_test.py
> +        self. TEST_NAME = test_name
Should I remove the test name and component completely as the thread_runner is also taking care?

2021-03-22 08:37 UTC, srijan-sivakumar commented on parent_test.py
> +        self. TEST_NAME = test_name
Better!

2021-03-22 09:15 UTC, srijan-sivakumar requested changes
The name mixin object also is a part of the parent class. Do check the latest changes pushed by Nishith for the naming convention to be used for this object.

2021-03-22 09:15 UTC, srijan-sivakumar commented on parent_test.py
> +        Creates volume
@aujjwal-redhat , I think you forgot the mixin object here :p

2021-03-22 09:19 UTC, aujjwal-redhat commented
> The name mixin object also is a part of the parent class. Do check the latest changes pushed by Nishith for the naming convention to be used for this object.

Oh ok.

2021-03-22 09:28 UTC, srijan-sivakumar approved these changes

2021-03-22 09:28 UTC, srijan-sivakumar commented
@aujjwal-redhat , just a nit..Could you modify the existing sample_tc.py and use this Parent class in the same ?

2021-03-22 09:32 UTC, aujjwal-redhat commented
> @aujjwal-redhat , just a nit..Could you modify the existing sample_tc.py and use this Parent class in the same ?

Yeah sure

2021-03-22 10:06 UTC, aujjwal-redhat commented
@srijan-sivakumar I have modified the sample_test.py file.
Called the sample_test.py file from another class; tested it with dummy variables.
```js
PASS = True
Redant = {'name': 'ayush'}
Test result = True
```
Got the above as the output

2021-03-22 10:23 UTC, srijan-sivakumar requested changes

2021-03-22 10:23 UTC, srijan-sivakumar commented on tests/sample_test.py
> +        super().__init__(redant=redant)
is this required ? Won't the child class automatically invoke the parent constructor ?

2021-03-22 10:25 UTC, aujjwal-redhat commented on tests/sample_test.py
> +        super().__init__(redant=redant)
so should we delete the __init__ of the test clas?

2021-03-22 10:28 UTC, srijan-sivakumar commented on tests/sample_test.py
> +        super().__init__(redant=redant)
Yes...in this scenario, it won't be required.

2021-03-22 10:28 UTC, aujjwal-redhat commented on tests/sample_test.py
> +        super().__init__(redant=redant)
I would suggest to remove it coz automatically the constructor is working the same in parent_Test. Moreover, if we aren't going to override anything else in the TestClass's init then it would be better to remove it.

2021-03-22 10:30 UTC, aujjwal-redhat commented on tests/sample_test.py
> +        super().__init__(redant=redant)
>Yes...in this scenario, it won't be required.

Ok will not remove it completely then

2021-03-22 10:33 UTC, srijan-sivakumar approved these changes

2021-03-22 10:33 UTC, merged