Created a pylintrc file
srijan-sivakumar/redant pull request #88
Opened 2021-03-17 11:15 UTC by aujjwal-redhat

Created a .pylintrc file using pylint --generate-rcfile > .pylintrc
Now we can modify the same for the warnings that are not actually errors

The warnings that I removed by adding them in the .pylintrc :
disable=E1101,
        E0401,
        R0801,
        R0903,
        C0103,
        W0703

Updates: #58
Signed-off-by: aujjwal-redhat <aujjwal@redhat.com>

2021-03-17 11:16 UTC, aujjwal-redhat commented on .github/workflows/linting.yml
> +          pylint $(pwd)/redant_libs/
This is temporary. We need to create packages. Then we won't need to provide absolute paths.

2021-03-17 11:19 UTC, nik-redhat commented
Could you also fix the errors being reported by the pylint in the workflow?

2021-03-17 11:21 UTC, aujjwal-redhat commented
> Could you also fix the errors being reported by the pylint in the checks?

Yeah sure

2021-03-17 11:44 UTC, aujjwal-redhat commented
Errors & Messages:

E1101:
'%s %r has no %r member%s'
https://pycodequ.al/docs/pylint-messages/e1101-no-member.html

In our code
E1101: Instance of 'VolumeOps' has no 'rlog' member (no-member)

E0401:
 Unable to import 'redant_libs.support_libs.rexe' (import-error)

R0801:
R0801: Similar lines in 5 files

R0903,

C0103,
C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
W0703:
W0703: Catching too general exception Exception (broad-except)

R0902
R0902: Too many instance attributes (12/7) (too-many-instance-attributes)

These were not errors actually. 
Few among these which I felt we can still have are:
W0703: Catching too general exception Exception (broad-except)
Coz we might need to have more specific exceptions rather than
```js
except Exception as e
```
and
C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
Coz it might help in making the code more consistent throughout the project.

2021-03-17 11:49 UTC, aujjwal-redhat commented on .pylintrc
> +
Here are the warnings that are disabled.

2021-03-17 12:04 UTC, nik-redhat commented
Is the import error that was being reported earlier fixed, or disabled?

2021-03-17 12:08 UTC, aujjwal-redhat commented
> Is the import error that was being reported earlier fixed, or disabled?

It is disabled for now.
The issue is we need to first create packages or either add pythonpath.
Adding pytohn path will not be a good choice as compared to creating packages.
That's why added the following too:
https://github.com/srijan-sivakumar/redant/pull/88#discussion_r595923628

2021-03-17 12:10 UTC, aujjwal-redhat commented
To regenerate the specific errors:
1. Remove the specific errors or all of them from disable in .pylintrc 
2. Then run the command:
```js
pylint -j 4 --rcfile=.pylintrc redant_libs/
```

2021-03-17 12:16 UTC, nik-redhat commented
Okay, do we have an issue open to track this? So, that we don't forget to fix it.

2021-03-17 12:17 UTC, aujjwal-redhat commented
> Okay, do we have an issue open to track this? So, that we don't forget to fix it.

Yeah I will add one with all the required info.

2021-03-17 12:20 UTC, nik-redhat commented
@srijan-sivakumar does it look fine to you?

2021-03-17 12:23 UTC, aujjwal-redhat commented
Added the issue #89 
@nik-redhat

2021-03-17 13:48 UTC, srijan-sivakumar commented on .github/workflows/linting.yml
> +          pylint $(pwd)/redant_libs/
What about the test cases ?

2021-03-17 13:49 UTC, srijan-sivakumar requested changes

2021-03-17 13:49 UTC, srijan-sivakumar commented on redant_libs/support_libs/rexe.py
> -        stdin, stdout, stderr = self.node_dict[node].exec_command(cmd)
No. this is not the way! rather it should be `_, stdout, stderr = self.node_dict[node].exec(cmd)`

2021-03-18 04:33 UTC, aujjwal-redhat commented on .github/workflows/linting.yml
> +          pylint $(pwd)/redant_libs/
Added now.

2021-03-18 04:43 UTC, srijan-sivakumar approved these changes

2021-03-18 04:43 UTC, merged