Adding GlusterOps library
srijan-sivakumar/redant pull request #92
Opened 2021-03-18 05:57 UTC by nishith-vihar

Gluster Ops lib is added which has functionalities
for stating and stopping glusterd service.

Fixes: #91
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

2021-03-18 10:36 UTC, nik-redhat commented on redant_libs/gluster_libs/gluster_ops.py
> +        cmd = "systemctl sto glusterd"
nit: stop

2021-03-18 10:37 UTC, nik-redhat commented on redant_libs/gluster_libs/gluster_ops.py
> +    def gluster_start(self, node: str):
make it `glusterd_start`. Same for below function as well

2021-03-18 10:39 UTC, nik-redhat commented on redant_libs/redant_mixin.py
> +from redant_libs.gluster_libs.gluster_ops import GlusterOps
why this difference in naming style?
`gluster_ops` looks better, and the same format should be used for `volume_ops`.

2021-03-18 10:45 UTC, nishith-vihar commented on redant_libs/redant_mixin.py
> +from redant_libs.gluster_libs.gluster_ops import GlusterOps
The naming convention for a class should be in PascalCase like GlusterOps and not like gluster_ops. So io_ops and peer_ops should also be changed accordingly.

2021-03-18 10:47 UTC, nik-redhat commented on redant_libs/redant_mixin.py
> +from redant_libs.gluster_libs.gluster_ops import GlusterOps
Ohh right, forgot that part :smile: 
Then, do update their naming to PascalCase.

2021-03-18 10:51 UTC, srijan-sivakumar commented on redant_libs/gluster_libs/gluster_ops.py
> +    def gluster_start(self, node: str):
+1

2021-03-18 10:52 UTC, nishith-vihar commented on redant_libs/gluster_libs/gluster_ops.py
> +    def gluster_start(self, node: str):
Fixed

2021-03-18 10:52 UTC, nishith-vihar commented on redant_libs/gluster_libs/gluster_ops.py
> +        cmd = "systemctl sto glusterd"
Fixed

2021-03-18 10:53 UTC, srijan-sivakumar requested changes

2021-03-18 10:53 UTC, srijan-sivakumar commented on redant_libs/gluster_libs/gluster_ops.py
> +    def glusterd_start(self, node: str):
Have you tried stopping and starting glusterd more than 5 times? Do try that operation. Also add the status function.

2021-03-18 10:56 UTC, nishith-vihar commented on redant_libs/gluster_libs/gluster_ops.py
> +    def glusterd_start(self, node: str):
Do i return a boolean value for status: True for active and false for inactive?

2021-03-18 10:57 UTC, nishith-vihar commented on redant_libs/gluster_libs/gluster_ops.py
> +    def glusterd_start(self, node: str):
I will make a seperate testcase for starting and stopping glusterd >5 times

2021-03-18 10:57 UTC, nik-redhat commented on redant_libs/gluster_libs/gluster_ops.py
> +    def glusterd_start(self, node: str):
Actually, we need many other libraries as well, like sometimes glusterd doesn't start immediately it takes time, check status and all. I thought it can be enhanced in the next iteration so skipped that.
But, only the reset failure can be done, if it's needed now.

2021-03-19 06:11 UTC, srijan-sivakumar commented on redant_libs/gluster_libs/gluster_ops.py
> +    def glusterd_start(self, node: str):
Cool. Then as we go.

2021-03-22 04:39 UTC, srijan-sivakumar approved these changes

2021-03-22 04:40 UTC, merged