Basic testcase added
srijan-sivakumar/redant pull request #99
Opened 2021-03-18 11:33 UTC by neesingh-rh

Added basic test case for peer ops library.

Updates: #93 
Signed-off-by: Neeraj Pratap Singh neesingh@redhat.com

2021-03-19 06:08 UTC, srijan-sivakumar requested changes

2021-03-19 06:08 UTC, srijan-sivakumar commented on tests/test_peer_probe_detach.py
> +            print("Test is running")
Nit. Remove this.

2021-03-19 06:08 UTC, srijan-sivakumar commented on tests/test_peer_probe_detach.py
> +            server_ip1 = self.remote_exec.get_server_ip("server_vm1")
Have you tried using the hostnames only from the connection stage itself ? So this conversion activity is not required.

2021-03-19 06:08 UTC, srijan-sivakumar commented on tests/test_peer_probe_detach.py
> +        except Exception as e:
Again, instead of print, we should return the value. Let the thread runner take care of reporting the failures.

2021-03-19 06:28 UTC, neesingh-rh commented on tests/test_peer_probe_detach.py
> +            server_ip1 = self.remote_exec.get_server_ip("server_vm1")
Actually, I tried with ips of servers during testing also..Thats why used params handler module.

2021-03-19 06:29 UTC, neesingh-rh commented on tests/test_peer_probe_detach.py
> +        except Exception as e:
okay

2021-03-22 04:56 UTC, srijan-sivakumar approved these changes

2021-03-22 05:01 UTC, nishith-vihar approved these changes

2021-03-22 05:06 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +class testcase:
Shouldn't the class naming follow the CamelCase convention?

2021-03-22 05:06 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +            self.remote_exec.gluster_start("192.168.122.220")
I guess the function name was changed to `glusterd_start`?

2021-03-22 05:06 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +                "192.168.122.161", "192.168.122.220", force=True)
Is glusterd already running on these servers?

2021-03-22 05:06 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +                "192.168.122.161", "192.168.122.220", force=True)
Why are you probing with `force`?

2021-03-22 05:06 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +            self.remote_exec.gluster_stop("192.168.122.220")
`glusterd_stop`

2021-03-22 05:06 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +                "192.168.122.220", "192.168.122.161", force=True)
Same as above

2021-03-22 05:11 UTC, neesingh-rh commented on tests/test_peer_probe_detach.py
> +            self.remote_exec.gluster_start("192.168.122.220")
Yeah..Will change it

2021-03-22 05:14 UTC, nishith-vihar requested changes

2021-03-22 05:14 UTC, nishith-vihar commented on tests/test_peer_probe_detach.py
> +class testcase:
Yeah you are right. That should be changed. The right way is 'TestCase'

2021-03-22 05:16 UTC, neesingh-rh commented on tests/test_peer_probe_detach.py
> +class testcase:
Yeah..My bad

2021-03-22 05:27 UTC, neesingh-rh commented on tests/test_peer_probe_detach.py
> +                "192.168.122.161", "192.168.122.220", force=True)
Actually,we are not supposed to. Will check this.

2021-03-22 05:27 UTC, neesingh-rh commented on tests/test_peer_probe_detach.py
> +                "192.168.122.161", "192.168.122.220", force=True)
yeah.

2021-03-22 05:30 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +                "192.168.122.161", "192.168.122.220", force=True)
How do you know that?

2021-03-22 05:49 UTC, neesingh-rh commented on tests/test_peer_probe_detach.py
> +                "192.168.122.161", "192.168.122.220", force=True)
These are my local machine VM's..I ran glusterd start on both servers

2021-03-22 06:01 UTC, nik-redhat commented on tests/test_peer_probe_detach.py
> +                "192.168.122.161", "192.168.122.220", force=True)
Okay... then for testing purposes use the `is_glusterd_active` function to confirm the status of glusterd and then do a peer probe.

2021-03-22 06:05 UTC, nik-redhat commented
Also, did you run the test case? Did it run successfully?

2021-03-22 06:34 UTC, neesingh-rh commented
> Also, did you run the test case? Did it run successfully?

yes..I did check...It was running.

2021-03-22 08:02 UTC, nishith-vihar requested changes
The remote_exec class variable has to be changed to redant. Refer to #106

2021-03-22 08:23 UTC, srijan-sivakumar commented
@neesingh-rh why are we pushing commits which are already part of the mainline code...Did you rebase the code? or just pulled the latest changes ?

2021-03-22 08:24 UTC, neesingh-rh commented
> @neesingh-rh why are we pushing commits which are already part of the mainline code...Did you rebase the code? or just pulled the latest changes ?

I did rebase

2021-03-22 10:29 UTC, closed without merging